'use client';
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {supabase,type Profile} from '@/lib/supabase';
import Demo from './demo';

function Users(){
 const [users,setUsers]=useState<Profile[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data,error}=await supabase.from('farm_profiles').select('*').order('created_at');if(error){setUsers([]);setMessage('Não foi possível consultar as contas.');}else setUsers(data||[])}
 useEffect(()=>{void load()},[]);
 async function update(user:Profile,role:Profile['role'],active:boolean){setBusy(true);setMessage('');try{const {error}=await supabase.rpc('farm_manage_user',{target:user.id,new_role:role,enabled:active});if(error)setMessage(error.message);else {setMessage('Conta atualizada.');await load()}}catch{setMessage('Sem conexão. Tente novamente.')}finally{setBusy(false)}}
 return <section className="panel users-panel"><h2>Usuários</h2><p>Novos cadastros aguardam confirmação do e-mail e aprovação. Administradores têm acesso aos custos e à gestão de usuários.</p><p role="status">{message}</p>{users.map(user=><article className="user-row" key={user.id}><div><strong>{user.name||user.email}</strong><p>{user.email}</p><small>{user.role==='administrador'?'Administrador':'Vendedor'} · {user.active?'Ativo':'Aguardando aprovação / desativado'}</small></div>{user.role==='vendedor'&&<div className="actions"><button disabled={busy} onClick={()=>update(user,'vendedor',!user.active)}>{user.active?'Desativar':'Aprovar vendedor'}</button><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm(`Dar acesso completo de administrador a ${user.email}?`))void update(user,'administrador',true)}}>Tornar administrador</button></div>}</article>)}<button className="secondary" onClick={load}>Atualizar lista</button></section>
}

export default function Auth(){
 const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[authError,setAuthError]=useState('');
 const [mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[users,setUsers]=useState(false);
 useEffect(()=>{let live=true;let revision=0;
  const resolve=async(next:Session|null)=>{const request=++revision;if(!live)return;setSession(next);setAuthError('');if(!next){setProfile(null);setUsers(false)}setLoading(true);if(next){try{const {data,error}=await supabase.from('farm_profiles').select('*').eq('id',next.user.id).single();if(live&&request===revision){if(error){setProfile(null);setAuthError('Não foi possível verificar seu acesso. Tente novamente.')}else setProfile(data)}}catch{if(live&&request===revision){setProfile(null);setAuthError('Sem conexão para verificar o acesso.')}}}if(live&&request===revision)setLoading(false)};
  void supabase.auth.getSession().then(({data,error})=>{if(error&&live){setAuthError('Não foi possível recuperar sua sessão.');setLoading(false)}else void resolve(data.session)});
  const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setTimeout(()=>{if(live)void resolve(next)},0)});
  return ()=>{live=false;revision++;subscription.unsubscribe()};
 },[]);
 async function signout(){setBusy(true);const {error}=await supabase.auth.signOut();setBusy(false);if(error)setAuthError('Não foi possível sair. Tente novamente.');else{setProfile(null);setSession(null);setPassword('');setMessage('')}}
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{
  if(mode==='signup'){const {error,data}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()},emailRedirectTo:window.location.origin}});if(error)setMessage(error.status===429?'Muitas tentativas. Aguarde alguns minutos.':'Não foi possível cadastrar. Confira os dados ou tente novamente mais tarde.');else{setPassword('');setMessage(data.session?'Cadastro realizado. Aguarde a aprovação do administrador.':'Confira seu e-mail para confirmar o cadastro. Se já possui conta, use Entrar.')}}
  else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage('Não foi possível entrar. Confira e-mail, senha e a confirmação do cadastro.');else setPassword('')}
 }catch{setMessage('Sem conexão. Tente novamente.')}finally{setBusy(false)}}
 if(loading)return <div className="auth-page"><section className="panel" role="status">Verificando acesso…</section></div>;
 if(session)return <>{profile?.active?<><div className="account-bar"><span>{profile.name||profile.email} · {profile.role==='administrador'?'Administrador':'Vendedor'}</span><div className="actions">{profile.role==='administrador'&&<button className="secondary" onClick={()=>setUsers(!users)}>{users?'Voltar à Farm':'Usuários'}</button>}<button className="secondary" disabled={busy} onClick={signout}>Sair</button></div></div>{authError&&<p role="alert">{authError}</p>}{users?<Users/>:<Demo key={profile.id} administrator={profile.role==='administrador'} userId={profile.id}/>}</>:<div className="auth-page"><section className="panel auth-card"><h1>{authError?'Acesso indisponível':'Aguardando aprovação'}</h1><p>{authError||'Seu cadastro foi recebido. Um administrador precisa liberar o acesso à Farm.'}</p><p>{session.user.email}</p><button onClick={()=>window.location.reload()}>Verificar novamente</button><button className="secondary" disabled={busy} onClick={signout}>Sair</button></section></div>}</>;
 return <div className="auth-page"><section className="panel auth-card"><img src="/brand/Logo_Otimizada_Preta.png" width="110" height="109" alt="Sonho em Camadas 3D"/><p className="eyebrow">GESTÃO DA FARM</p><h1>{mode==='login'?'Entrar na sua Farm':'Criar conta'}</h1><p>{mode==='login'?'Acesse com seu e-mail e senha.':'O administrador aprovará seu acesso como vendedor.'}</p><form onSubmit={submit}>{mode==='signup'&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} required maxLength={120} autoComplete="name"/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='signup'?8:undefined} required autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='signup'&&<small>Use pelo menos 8 caracteres. Confirme o cadastro pelo e-mail recebido.</small>}<button disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar':'Cadastrar'}</button></form><p role="status">{message||authError}</p><button disabled={busy} className="secondary" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('');setPassword('')}}>{mode==='login'?'Ainda não tenho conta':'Já tenho conta'}</button></section></div>
}
