'use client';
import {useState,useReducer} from 'react';
import ProductSheet from './product-sheet';
import {useDemoTool} from '@/lib/use-demo-tool';
import {LayoutDashboard,Package,ReceiptText,Printer,Boxes,Wallet,Layers,ArrowRight,RotateCcw,CheckCircle2} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {cost,money,initial,reduce} from '@/lib/demo';
const nav=[['Visão geral',LayoutDashboard],['Produtos e custos',Package],['Pedidos',ReceiptText],['Produção',Printer],['Estoque',Boxes],['Recebimentos',Wallet]] as const;
function Menu({page,go,administrator}:{page:number;go:(v:number)=>void;administrator:boolean}){const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader><div className="brand official-brand"><img src="brand/Logo_Otimizada_Preta.png" alt="Sonho em Camadas 3D — Ideias que ganham forma" width="180" height="178"/><small>GESTÃO DA FARM</small></div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(([label,Icon],i)=>!administrator&&(i===1||i===3||i===4)?null:<SidebarMenuItem key={label}><SidebarMenuButton isActive={page===i} onClick={()=>{go(i);setOpenMobile(false)}}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="workspace"><span className="avatar">SC</span><div>Sonho em Camadas 3D<small>Ambiente de demonstração</small></div></div></SidebarFooter></Sidebar>}
function GridTable({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <Table><TableHeader><TableRow>{heads.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>}
export default function Demo({administrator,userId}:{administrator:boolean;userId:string}){const [page,go]=useState(0),[pla,setPla]=useState(100),[margin,setMargin]=useState(35),[amount,setAmount]=useState('40'),[notice,setNotice]=useState('');const [s,dispatch]=useReducer(reduce,initial);const unit=cost(pla),received=s.payments.reduce((a,b)=>a+b,0),balance=s.confirmed?210-received:0;const send=(type:Parameters<typeof reduce>[1]['type'],value?:number)=>{dispatch({type,value});setNotice(type==='reset'?'Exemplo reiniciado.':'Simulação atualizada.');};
useDemoTool(s); const badge=(text:string)=><span className="badge">{text}</span>;
return <SidebarProvider><Menu page={page} go={go} administrator={administrator}/><main><header><div className="crumb"><SidebarTrigger/>Farm <span>/</span> {nav[page][0]}</div><span className="demo-pill">● Protótipo</span></header><div className="canvas"><div className="heading"><div><p className="eyebrow">SUA FARM, EM CADA ETAPA</p><h1>{nav[page][0]}</h1><p>{page===0?'Da primeira camada ao último recebimento.':'Cenário de revisão · setembro de 2026'}</p></div><button className="secondary" onClick={()=>{send('reset');setPla(100);setMargin(35);setAmount('40')}}><RotateCcw size={16}/> Reiniciar exemplo</button></div><div className="demo-note">{page===1 ? "Ficha editável: salve na sua conta para recuperar em outros aparelhos. Confira as bases de cálculo antes de usar o preço." : "Pedidos e recebimentos usam dados fictícios e reiniciam ao recarregar. A ficha de custos é exclusiva do administrador."}</div><div aria-live="polite" className="notice">{notice}</div>
{page===0&&<><div className="metrics">{[['Vendas confirmadas',money(s.confirmed?210:0),'Pedidos confirmados neste cenário'],['Recebido',money(received),'Pagamentos registrados neste cenário'],['A receber',money(balance),'Saldo das vendas confirmadas'],['Produção pendente',`${s.confirmed?10-s.approved:0} un.`,s.confirmed?'Vasos ainda não aprovados':'Confirme o pedido para começar']].map(([a,b,c])=><article key={a}><p>{a}</p><strong>{b}</strong><small>{c}</small></article>)}</div><div className="split"><section className="panel"><div className="section-title"><h2>Um pedido, todas as etapas</h2>{badge('#1042')}</div><p className="muted">Marina Costa · 10 vasos e 2 chaveiros</p><div className="journey">{[['Confirmar pedido',s.confirmed,2],['Produzir 10 vasos',s.approved===10,3],['Entregar os itens',s.delivered,4],['Receber R$ 210',received===210,5]].map(([label,done,target],i)=><button key={i} disabled={!administrator&&(Number(target)===3||Number(target)===4)} onClick={()=>go(Number(target))}><span className={done?'step done':'step'}>{done?<CheckCircle2 size={19}/>:i+1}</span><span>{label}</span><span className="muted">{done?'Concluído':'Revisar'}</span><ArrowRight size={17}/></button>)}</div></section><section className="panel accent-panel"><p className="eyebrow">COMECE POR AQUI</p><h2>Quanto custa<br/>cada peça?</h2><p>Preencha a ficha do seu produto e confira o preço sugerido.</p><p className="footnote">Ficha editável com materiais e taxas</p><button disabled={!administrator} onClick={()=>go(1)}>Calcular meu produto <ArrowRight size={17}/></button></section></div><section className="panel"><h2>Pontos para decidir juntos</h2><div className="decisions"><p><strong>01 · Reserva</strong>Na confirmação ou após o sinal?</p><p><strong>02 · Perdas</strong>Qual base usar para falhas e descarte?</p><p><strong>03 · Entrega</strong>Permitir entregas parciais?</p></div></section></>}
{administrator&&<div hidden={page!==1}><ProductSheet userId={userId}/></div>}{page===2&&<section className="panel"><div className="section-title"><div><h2>Pedido #1042</h2><p className="muted">Marina Costa · cliente fictícia · entrega prevista 15/09/2026</p></div>{badge(s.confirmed?'Confirmado':'Rascunho')}</div><GridTable heads={['Produto','Quantidade','Preço unitário','Custo unitário','Subtotal']} rows={[[<strong>Vaso Aurora</strong>,10,'R$ 20,00',money(s.confirmed?s.frozen:unit),'R$ 200,00'],['Chaveiro Camadas',2,'R$ 5,00','R$ 2,00','R$ 10,00']]}/><div className="order-total"><span>Sem desconto ou despesas · canal direto</span><strong>Total R$ 210,00</strong></div><p className="callout">{s.confirmed?'Preço e custo congelados na confirmação. Mudanças no catálogo não alteram este pedido.':'Ao confirmar, guardamos os valores deste pedido e reservamos os 2 chaveiros disponíveis. Os vasos serão reservados conforme produzidos.'}</p><div className="actions"><button disabled={s.confirmed} onClick={()=>send('confirm',unit)}>{s.confirmed?'Pedido confirmado':'Confirmar pedido'}</button><button disabled={!administrator} className="secondary" onClick={()=>go(3)}>Ver produção <ArrowRight size={16}/></button></div><div className="decisions"><p><strong>Produção</strong>{s.approved===10?'Concluída':s.started?'Em andamento':'Aguardando'}</p><p><strong>Pagamento</strong>{received===210?'Pago':received>0?'Parcial':'Não recebido'}</p><p><strong>Entrega</strong>{s.delivered?'Entregue':'Pendente'}</p></div></section>}
{administrator&&page===3&&<section className="panel"><div className="section-title"><h2>OP-028 · Vaso Aurora</h2>{badge(s.approved===10?'Concluída':s.started?'Imprimindo':'Aguardando')}</div><p className="muted">Pedido #1042 · Bambu A1 (exemplo) · prioridade normal · prazo 14/09/2026</p><div className="production-count"><strong>{s.approved}<span> / 10</span></strong><p>unidades aprovadas<br/><b>{10-s.approved} pendentes</b></p></div><div className="track"><div style={{width:`${s.approved*10}%`}}/></div><p className="callout">Aprovar peças gera entrada e reserva no estoque. Uma peça pendente ainda precisa ser produzida ou aprovada; não é automaticamente uma falha.</p><div className="actions"><button disabled={!s.confirmed||s.started} onClick={()=>send('start')}>Iniciar produção</button><button disabled={!s.started||s.approved!==0} onClick={()=>send('produce',8)}>Aprovar 8 unidades</button><button disabled={s.approved!==8} onClick={()=>send('produce',2)}>Aprovar 2 restantes</button></div>{!s.confirmed&&<p className="muted">Confirme o pedido antes de iniciar.</p>}<p className="footnote">Previsão original: 6 h e 300 g. Consumo real, falhas, reimpressões e agenda de máquinas ficam para a implementação operacional.</p></section>}
{administrator&&page===4&&<><section className="panel"><div className="section-title"><h2>Estoque de produtos</h2>{badge('Local · farm')}</div><GridTable heads={['Produto','Físico','Reservado','Disponível']} rows={[[ 'Vaso Aurora',s.delivered?0:s.approved,s.delivered?0:s.approved,0],['Chaveiro Camadas',s.delivered?0:2,s.confirmed&&!s.delivered?2:0,s.confirmed?0:2]]}/><div className="actions"><button disabled={s.approved!==10||s.delivered} onClick={()=>send('deliver')}>{s.delivered?'Pedido entregue':'Entregar pedido #1042'}</button><span className="muted">Entrega integral após 10 vasos aprovados.</span></div></section><section className="panel"><h2>Histórico de movimentações</h2>{s.movements.map((m,i)=><div className="movement" key={i}><span><small>Movimento {String(i+1).padStart(2,'0')}</small>{m.name}</span><strong>{m.qty}</strong></div>)}</section></>}
{page===5&&<div className="split"><section className="panel"><h2>Receber · pedido #1042</h2><p className="muted">Marina Costa · vencimento de exemplo: 15/09/2026</p><div className="metrics compact"><article><p>Recebido</p><strong>{money(received)}</strong></article><article><p>Saldo</p><strong>{money(balance)}</strong></article></div><form onSubmit={e=>{e.preventDefault();const n=Number(amount.replace(',','.'));if(!s.confirmed||!Number.isFinite(n)||n<=0||Math.round(n*100)>Math.round(balance*100)){setNotice('Informe um valor positivo até o saldo e confirme o pedido.');return}send('pay',n)}}><label>Valor recebido (R$)<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button disabled={!s.confirmed||balance===0}>Registrar recebimento fictício</button></form>{!s.confirmed&&<p className="muted">Confirme o pedido para registrar pagamentos.</p>}<p className="footnote">Exemplo: R$ 210 − R$ 40 = R$ 170 a receber. Registrar pagamento não conclui produção nem entrega.</p></section><section className="panel"><h2>Histórico de recebimentos</h2>{s.payments.length?s.payments.map((p,i)=><div className="movement" key={i}><span>Recebimento {i+1}<small>Simulação · Pix</small></span><strong>{money(p)}</strong></div>):<div className="empty"><Wallet size={30}/><h3>Nenhum recebimento</h3><p>Os pagamentos aparecerão aqui após o registro.</p></div>}</section></div>}
<footer>SONHO EM CAMADAS 3D <span>Protótipo 01 · revisão do fluxo · sem dados reais</span></footer></div></main></SidebarProvider>}






