'use client';
/* oxlint-disable next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,ExternalLink,FilterX,ImagePlus,Pencil,Plus,RefreshCw,RotateCcw,Search,ShoppingBag,Trash2,UserRoundCheck,XCircle} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {type Seller} from './seller-registry';
import './orders.css';

type OrderItem={id:string;produto_id:string|null;produto_nome:string;quantidade:number;preco_unitario:number;tipo:'portfolio'|'novo_produto';detalhes:string|null;link_referencia:string|null;foto_urls:string[];estoque_baixado:number;producao_necessaria:number};
type Order={id:string;numero:number;cliente_nome:string;cliente_telefone:string|null;cliente_email:string|null;cliente_documento:string|null;endereco_entrega:string|null;vendedor_id:string|null;vendedor_cadastro_id:string|null;vendedor_nome:string;data_pedido:string;prazo_solicitado:string|null;forma_pagamento:string|null;observacoes:string|null;motivo_cancelamento:string|null;decisao_observacao:string|null;subtotal:number;desconto_percentual:number;valor_venda_informado:number|null;valor_total:number;status:string;items:OrderItem[]};
type RawOrder=Omit<Order,'items'>&{itens:OrderItem[]|null};
type Product={airtable_record_id:string;nome:string;preco_venda:number|null;estoque:number|null;foto_urls:string[]};
type SelectedItem={quantity:number;price:number};
type NewProduct={key:string;name:string;quantity:number;price:string;details:string;link:string;photo_urls:string[];files:File[]};
type OrderForm={cliente_nome:string;cliente_telefone:string;cliente_email:string;cliente_documento:string;endereco_entrega:string;vendedor_cadastro_id:string;prazo_solicitado:string;forma_pagamento:string;observacoes:string};

const emptyForm:OrderForm={cliente_nome:'',cliente_telefone:'',cliente_email:'',cliente_documento:'',endereco_entrega:'',vendedor_cadastro_id:'',prazo_solicitado:'',forma_pagamento:'',observacoes:''};
const reais=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),environment=import.meta.env.BASE_URL.includes('/desenvolvimento/')?'desenvolvimento':'producao';
const pricingStatuses=new Set(['aguardando_precificacao','em_precificacao','precificado','aguardando_confirmacao_vendedor']),editableStatuses=new Set(['rascunho','aguardando_precificacao','em_precificacao','precificado','aguardando_confirmacao_vendedor','aguardando_aprovacao','devolvido_ajuste']),cancellableStatuses=new Set(editableStatuses);
const statusLabels:Record<string,string>={rascunho:'Rascunho',aguardando_precificacao:'Aguardando precificação',em_precificacao:'Em precificação',precificado:'Precificado',aguardando_confirmacao_vendedor:'Aguardando confirmação',aguardando_aprovacao:'Aguardando aprovação',devolvido_ajuste:'Devolvido para ajuste',reprovado:'Reprovado',aprovado:'Aprovado',em_producao:'Em produção',pronto:'Pronto',entregue:'Entregue',cancelado:'Cancelado'};
const formatDate=(value:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'Não informado',orderNumber=(value:number)=>`#${String(value).padStart(4,'0')}`,makeNewProduct=():NewProduct=>({key:crypto.randomUUID(),name:'',quantity:1,price:'',details:'',link:'',photo_urls:[],files:[]});

export default function Orders({administrator,userId}:{administrator:boolean;userId:string}){
 const draftKey=`farm.orderDraft.${environment}.${userId}`;
 const [orders,setOrders]=useState<Order[]>([]),[sellers,setSellers]=useState<Seller[]>([]),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [query,setQuery]=useState(''),[status,setStatus]=useState('todos'),[sellerFilter,setSellerFilter]=useState('todos'),[period,setPeriod]=useState('todos'),[today]=useState(()=>new Date());
 const [formOpen,setFormOpen]=useState(false),[editingOrder,setEditingOrder]=useState<Order|null>(null),[form,setForm]=useState<OrderForm>(emptyForm),[selectedItems,setSelectedItems]=useState<Record<string,SelectedItem>>({}),[newProducts,setNewProducts]=useState<NewProduct[]>([]),[discount,setDiscount]=useState('0'),[directSalePrice,setDirectSalePrice]=useState(''),[saving,setSaving]=useState(false),[deciding,setDeciding]=useState<string|null>(null),[draftReady,setDraftReady]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');let request=supabase.from('farm_orders').select('id,numero,cliente_nome,cliente_telefone,cliente_email,cliente_documento,endereco_entrega,vendedor_id,vendedor_cadastro_id,vendedor_nome,data_pedido,prazo_solicitado,forma_pagamento,observacoes,motivo_cancelamento,decisao_observacao,subtotal,desconto_percentual,valor_venda_informado,valor_total,status,itens:farm_order_items(id,produto_id,produto_nome,quantidade,preco_unitario,tipo,detalhes,link_referencia,foto_urls,estoque_baixado,producao_necessaria)').eq('ambiente',environment).order('data_pedido',{ascending:false}).order('numero',{ascending:false});if(!administrator)request=request.eq('vendedor_id',userId);const [ordersResult,sellersResult,productsResult]=await Promise.all([request,supabase.from('farm_sellers').select('id,nome,telefone,email,usuario_id,ativo').eq('ambiente',environment).order('nome'),supabase.from('farm_portfolio_products').select('airtable_record_id,nome,preco_venda,estoque,foto_urls').eq('ativo',true).eq('exibir_portfolio',true).not('preco_venda','is',null).order('nome')]);if(ordersResult.error||sellersResult.error||productsResult.error){setError('Não foi possível carregar os dados de pedidos.');setOrders([])}else{setOrders(((ordersResult.data||[]) as unknown as RawOrder[]).map(order=>({...order,numero:Number(order.numero),subtotal:Number(order.subtotal),desconto_percentual:Number(order.desconto_percentual),valor_venda_informado:order.valor_venda_informado===null?null:Number(order.valor_venda_informado),valor_total:Number(order.valor_total),items:(order.itens||[]).map(item=>({...item,quantidade:Number(item.quantidade),preco_unitario:Number(item.preco_unitario),estoque_baixado:Number(item.estoque_baixado),producao_necessaria:Number(item.producao_necessaria)}))})));setSellers((sellersResult.data||[]) as Seller[]);setProducts((productsResult.data||[]) as Product[])}setLoading(false)},[administrator,userId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const stored=sessionStorage.getItem(draftKey);if(stored){const draft=JSON.parse(stored) as {form:OrderForm;selectedItems:Record<string,SelectedItem>;newProducts:NewProduct[];discount:string;directSalePrice:string;editingOrder:Order|null};setForm(draft.form);setSelectedItems(draft.selectedItems||{});setNewProducts((draft.newProducts||[]).map(item=>({...item,files:[]})));setDiscount(draft.discount||'0');setDirectSalePrice(draft.directSalePrice||'');setEditingOrder(draft.editingOrder||null);setFormOpen(true);setMessage('Rascunho do pedido recuperado nesta janela.')}}catch{sessionStorage.removeItem(draftKey)}setDraftReady(true)},0);return()=>window.clearTimeout(timer)},[draftKey]);
 useEffect(()=>{if(!draftReady)return;if(!formOpen){sessionStorage.removeItem(draftKey);return}const serializableProducts=newProducts.map(item=>({...item,files:[]}));sessionStorage.setItem(draftKey,JSON.stringify({form,selectedItems,newProducts:serializableProducts,discount,directSalePrice,editingOrder}))},[directSalePrice,discount,draftKey,draftReady,editingOrder,form,formOpen,newProducts,selectedItems]);
 const linkedSeller=sellers.find(item=>item.usuario_id===userId&&item.ativo),selectableSellers=sellers.filter(item=>item.ativo),selectedProducts=products.filter(product=>selectedItems[product.airtable_record_id]);
 const subtotal=selectedProducts.reduce((sum,p)=>sum+selectedItems[p.airtable_record_id].quantity*selectedItems[p.airtable_record_id].price,0)+newProducts.reduce((sum,p)=>sum+p.quantity*(Number(p.price.replace(',','.'))||0),0),discountNumber=Math.min(100,Math.max(0,Number(discount.replace(',','.'))||0)),discountValue=Math.round(subtotal*discountNumber)/100,discountedTotal=Math.round((subtotal-discountValue)*100)/100,directSaleNumber=directSalePrice.trim()===''?null:Number(directSalePrice.replace(',','.')),total=directSaleNumber!==null&&Number.isFinite(directSaleNumber)?directSaleNumber:discountedTotal,needsPricing=newProducts.some(item=>!item.price.trim()||Number(item.price.replace(',','.'))<=0);
 const sellerNames=useMemo(()=>Array.from(new Map(orders.map(order=>[order.vendedor_cadastro_id||order.vendedor_id||order.vendedor_nome,order.vendedor_nome])).entries()).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')),[orders]);
 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR').replace(/^#/,'');const cutoff=period==='todos'?null:new Date(today.getTime()-Number(period)*86400000).toISOString().slice(0,10);return orders.filter(order=>{const sellerKey=order.vendedor_cadastro_id||order.vendedor_id||order.vendedor_nome;return(!term||[order.numero,order.cliente_nome,...order.items.map(item=>item.produto_nome)].join(' ').toLocaleLowerCase('pt-BR').includes(term))&&(status==='todos'||order.status===status)&&(sellerFilter==='todos'||sellerKey===sellerFilter)&&(!cutoff||order.data_pedido>=cutoff)})},[orders,period,query,sellerFilter,status,today]);
 const approvalCount=orders.filter(o=>o.status==='aguardando_aprovacao').length,pricingCount=orders.filter(o=>pricingStatuses.has(o.status)).length,hasFilters=query!==''||status!=='todos'||sellerFilter!=='todos'||period!=='todos';
 function clearForm(){sessionStorage.removeItem(draftKey);setForm(emptyForm);setSelectedItems({});setNewProducts([]);setDiscount('0');setDirectSalePrice('');setEditingOrder(null);setFormOpen(false);setMessage('')}
 function startCreate(){if(formOpen){document.querySelector('.order-form')?.scrollIntoView({behavior:'smooth',block:'start'});return}setEditingOrder(null);setSelectedItems({});setNewProducts([]);setDiscount('0');setDirectSalePrice('');setForm({...emptyForm,vendedor_cadastro_id:administrator?'':linkedSeller?.id||''});setMessage('');setFormOpen(true)}
 function startEdit(order:Order){setEditingOrder(order);setForm({cliente_nome:order.cliente_nome,cliente_telefone:order.cliente_telefone||'',cliente_email:order.cliente_email||'',cliente_documento:order.cliente_documento||'',endereco_entrega:order.endereco_entrega||'',vendedor_cadastro_id:order.vendedor_cadastro_id||'',prazo_solicitado:order.prazo_solicitado||'',forma_pagamento:order.forma_pagamento||'',observacoes:order.observacoes||''});setSelectedItems(Object.fromEntries(order.items.filter(i=>i.produto_id).map(i=>[i.produto_id as string,{quantity:i.quantidade,price:i.preco_unitario}])));setNewProducts(order.items.filter(i=>i.tipo==='novo_produto').map(i=>({key:i.id,name:i.produto_nome,quantity:i.quantidade,price:i.preco_unitario?String(i.preco_unitario):'',details:i.detalhes||'',link:i.link_referencia||'',photo_urls:i.foto_urls||[],files:[]})));setDiscount(String(order.desconto_percentual));setDirectSalePrice(order.valor_venda_informado===null?'':String(order.valor_venda_informado));setFormOpen(true);setMessage('');window.setTimeout(()=>document.querySelector('.order-form')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}
 const updateNew=(key:string,changes:Partial<NewProduct>)=>setNewProducts(current=>current.map(item=>item.key===key?{...item,...changes}:item));

 async function saveOrder(target:'rascunho'|'aguardando_aprovacao'){
  setMessage('');if(!form.cliente_nome.trim()||!form.cliente_telefone.trim()){setMessage('Informe o nome e o telefone do cliente.');return}if(!selectedProducts.length&&!newProducts.length){setMessage('Adicione pelo menos um produto.');return}if(newProducts.some(item=>!item.name.trim()||item.quantity<1)){setMessage('Informe nome e quantidade dos produtos novos.');return}if(directSaleNumber!==null&&(!Number.isFinite(directSaleNumber)||directSaleNumber<0)){setMessage('Informe um valor de venda válido.');return}
  const seller=sellers.find(item=>item.id===form.vendedor_cadastro_id);if(form.vendedor_cadastro_id&&!seller){setMessage('O vendedor selecionado não está disponível.');return}setSaving(true);let orderId=editingOrder?.id||null;const uploaded:string[]=[];
  try{const values={cliente_nome:form.cliente_nome.trim(),cliente_telefone:form.cliente_telefone.trim(),cliente_email:form.cliente_email.trim()||null,cliente_documento:form.cliente_documento.trim()||null,endereco_entrega:form.endereco_entrega.trim()||null,vendedor_cadastro_id:seller?.id||null,vendedor_id:seller?.usuario_id||(!administrator?userId:null),vendedor_nome:seller?.nome||'Sem vendedor',prazo_solicitado:form.prazo_solicitado||null,forma_pagamento:form.forma_pagamento||null,observacoes:form.observacoes.trim()||null,subtotal:Math.round(subtotal*100)/100,desconto_percentual:discountNumber,valor_venda_informado:directSaleNumber,valor_total:Math.round(total*100)/100,atualizado_em:new Date().toISOString()};if(!orderId){const {data,error}=await supabase.from('farm_orders').insert({...values,status:'rascunho',ambiente:environment}).select('id').single();if(error||!data)throw error;orderId=(data as {id:string}).id}else{const {error}=await supabase.from('farm_orders').update(values).eq('id',orderId);if(error)throw error;const {error:deleteError}=await supabase.from('farm_order_items').delete().eq('pedido_id',orderId);if(deleteError)throw deleteError}
   const portfolioItems=selectedProducts.map(p=>({pedido_id:orderId,produto_id:p.airtable_record_id,produto_nome:p.nome,quantidade:selectedItems[p.airtable_record_id].quantity,preco_unitario:selectedItems[p.airtable_record_id].price,tipo:'portfolio'})),customItems=[];for(const item of newProducts){const urls=[...item.photo_urls];for(const file of item.files.slice(0,5)){const path=`${userId}/${orderId}/${crypto.randomUUID()}.${file.name.split('.').pop()?.toLowerCase()||'jpg'}`;const {error}=await supabase.storage.from('orders').upload(path,file,{contentType:file.type||undefined});if(error)throw error;uploaded.push(path);urls.push(supabase.storage.from('orders').getPublicUrl(path).data.publicUrl)}customItems.push({pedido_id:orderId,produto_id:null,produto_nome:item.name.trim(),quantidade:item.quantity,preco_unitario:Number(item.price.replace(',','.'))||0,tipo:'novo_produto',detalhes:item.details.trim()||null,link_referencia:item.link.trim()||null,foto_urls:urls})}
   const {error:itemError}=await supabase.from('farm_order_items').insert([...portfolioItems,...customItems]);if(itemError)throw itemError;const finalStatus=target==='aguardando_aprovacao'&&needsPricing?'aguardando_precificacao':target;const {error:statusError}=await supabase.from('farm_orders').update({status:finalStatus,atualizado_em:new Date().toISOString()}).eq('id',orderId);if(statusError)throw statusError;clearForm();setMessage(finalStatus==='rascunho'?'Pedido salvo como rascunho.':finalStatus==='aguardando_precificacao'?'Solicitação enviada para precificação.':'Pedido enviado para aprovação.');await load()
  }catch{if(uploaded.length)await supabase.storage.from('orders').remove(uploaded);setMessage('Não foi possível salvar o pedido. Confira os dados.')}finally{setSaving(false)}
 }
 async function approve(order:Order){setDeciding(order.id);const {data,error}=await supabase.rpc('farm_approve_order',{p_order_id:order.id});if(error)setMessage(error.message);else{const result=data as {estoque_baixado:number;producao_criada:number};setMessage(result.producao_criada?`Pedido aprovado: ${result.estoque_baixado} unidade(s) baixadas e ${result.producao_criada} enviada(s) para produção.`:`Pedido aprovado: ${result.estoque_baixado} unidade(s) baixadas do estoque.`);await load()}setDeciding(null)}
 async function decide(order:Order,target:'devolvido_ajuste'|'reprovado'){const note=window.prompt(target==='reprovado'?'Informe o motivo da reprovação:':'Informe o ajuste necessário:')?.trim();if(!note)return;setDeciding(order.id);const {error}=await supabase.from('farm_orders').update({status:target,decisao_observacao:note,atualizado_em:new Date().toISOString()}).eq('id',order.id);setMessage(error?'Não foi possível registrar a decisão.':target==='reprovado'?'Pedido reprovado.':'Pedido devolvido para ajuste.');if(!error)await load();setDeciding(null)}
 async function cancelOrder(order:Order){const reason=window.prompt(`Informe o motivo do cancelamento do pedido ${orderNumber(order.numero)}:`)?.trim();if(!reason)return;const {error}=await supabase.from('farm_orders').update({status:'cancelado',motivo_cancelamento:reason,cancelado_em:new Date().toISOString(),cancelado_por:userId,atualizado_em:new Date().toISOString()}).eq('id',order.id);setMessage(error?'Não foi possível cancelar o pedido.':`Pedido ${orderNumber(order.numero)} cancelado.`);if(!error)await load()}
 const canEdit=(order:Order)=>editableStatuses.has(order.status)&&(administrator||['rascunho','devolvido_ajuste','aguardando_confirmacao_vendedor'].includes(order.status)),canCancel=(order:Order)=>cancellableStatuses.has(order.status)&&(administrator||order.vendedor_id===userId);

 return <section className="orders-module" aria-label="Gestão de pedidos"><div className="order-page-actions"><button type="button" onClick={startCreate}><Plus size={17}/> {formOpen?'Continuar preenchimento':'Criar pedido'}</button></div>
  {formOpen&&<section className="panel order-form"><div className="orders-title"><div><h2>{editingOrder?`Alterar pedido ${orderNumber(editingOrder.numero)}`:'Criar pedido'}</h2><p className="muted">Adicione itens do Portfólio ou solicite um produto novo.</p></div></div><div className="order-form-fields"><label>Cliente<input value={form.cliente_nome} onChange={e=>setForm({...form,cliente_nome:e.target.value})} required/></label><label>Telefone ou WhatsApp<input value={form.cliente_telefone} onChange={e=>setForm({...form,cliente_telefone:e.target.value})} required inputMode="tel"/></label><label>E-mail<input type="email" value={form.cliente_email} onChange={e=>setForm({...form,cliente_email:e.target.value})}/></label><label>CPF/CNPJ<input value={form.cliente_documento} onChange={e=>setForm({...form,cliente_documento:e.target.value})}/></label><label>Vendedor (opcional)<select value={form.vendedor_cadastro_id} onChange={e=>setForm({...form,vendedor_cadastro_id:e.target.value})} disabled={!administrator}><option value="">Sem vendedor</option>{selectableSellers.map(item=><option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>Prazo solicitado<input type="date" value={form.prazo_solicitado} onChange={e=>setForm({...form,prazo_solicitado:e.target.value})}/></label><label>Forma de pagamento<select value={form.forma_pagamento} onChange={e=>setForm({...form,forma_pagamento:e.target.value})}><option value="">Selecione</option><option>Pix</option><option>Dinheiro</option><option>Cartão de débito</option><option>Cartão de crédito</option><option>Transferência</option></select></label><label className="wide-field">Endereço de entrega<input value={form.endereco_entrega} onChange={e=>setForm({...form,endereco_entrega:e.target.value})}/></label><label className="wide-field">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})} rows={3}/></label></div>
   <fieldset className="order-products"><legend>Produtos do Portfólio</legend>{products.map(product=>{const item=selectedItems[product.airtable_record_id];return <article className={item?'order-product selected':'order-product'} key={product.airtable_record_id}><label><input type="checkbox" checked={Boolean(item)} onChange={e=>setSelectedItems(current=>{const updated={...current};if(e.target.checked)updated[product.airtable_record_id]={quantity:1,price:Number(product.preco_venda)||0};else delete updated[product.airtable_record_id];return updated})}/>{product.foto_urls?.[0]?<img src={product.foto_urls[0]} alt=""/>:<span className="order-product-placeholder"><ShoppingBag size={18}/></span>}<span><strong>{product.nome}</strong><small>{reais.format(Number(product.preco_venda)||0)} · {product.estoque??0} em estoque</small></span></label>{item&&<label className="order-quantity">Quantidade<input type="number" min="1" value={item.quantity} onChange={e=>setSelectedItems(current=>({...current,[product.airtable_record_id]:{...item,quantity:Math.max(1,Math.floor(Number(e.target.value))||1)}}))}/></label>}</article>})}</fieldset>
   <section className="new-products-section"><div className="section-title"><div><h3>Produto novo</h3><p className="muted">Sem preço, o pedido seguirá primeiro para precificação.</p></div><button type="button" className="secondary" onClick={()=>setNewProducts(current=>[...current,makeNewProduct()])}><ImagePlus size={17}/> Adicionar produto novo</button></div>{newProducts.map((item,index)=><article className="new-product-card" key={item.key}><div className="new-product-title"><strong>Produto novo {index+1}</strong><button type="button" className="secondary" onClick={()=>setNewProducts(current=>current.filter(p=>p.key!==item.key))}><Trash2 size={15}/> Remover</button></div><div className="new-product-fields"><label>Nome<input value={item.name} onChange={e=>updateNew(item.key,{name:e.target.value})} required/></label><label>Quantidade<input type="number" min="1" value={item.quantity} onChange={e=>updateNew(item.key,{quantity:Math.max(1,Number(e.target.value)||1)})}/></label><label>Preço unitário (R$)<input type="number" min="0" step="0.01" value={item.price} onChange={e=>updateNew(item.key,{price:e.target.value})} placeholder="Deixe vazio para precificar"/></label><label className="wide-field">Detalhes<textarea value={item.details} onChange={e=>updateNew(item.key,{details:e.target.value})} rows={3} placeholder="Cores, tamanho e personalização"/></label><label className="wide-field">Link de referência<input type="url" value={item.link} onChange={e=>updateNew(item.key,{link:e.target.value})} placeholder="https://..."/></label><label className="wide-field">Fotos de referência<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple onChange={e=>updateNew(item.key,{files:Array.from(e.target.files||[]).slice(0,5)})}/><small className="field-hint">Até 5 imagens. {item.files.length?`${item.files.length} selecionada(s).`:item.photo_urls.length?`${item.photo_urls.length} salva(s).`:''}</small></label></div></article>)}</section>
   <div className="order-price-fields"><label>Desconto (%)<input type="number" min="0" max="100" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Valor final informado (R$)<input type="number" min="0" step="0.01" value={directSalePrice} onChange={e=>setDirectSalePrice(e.target.value)} placeholder={reais.format(discountedTotal)}/></label></div><div className="order-price-summary"><div><span>Subtotal</span><strong>{reais.format(subtotal)}</strong></div><div><span>Desconto</span><strong>- {reais.format(discountValue)}</strong></div><div className="order-form-total"><span>Total</span><strong>{reais.format(Math.max(0,total))}</strong></div></div>{needsPricing&&<div className="pricing-alert"><Clock3 size={18}/> Produto novo sem preço: será enviado para precificação.</div>}{message&&<output className="notice">{message}</output>}<div className="order-form-actions"><button type="button" disabled={saving} onClick={()=>void saveOrder('aguardando_aprovacao')}>{saving?'Salvando…':needsPricing?'Enviar para precificação':'Enviar para aprovação'}</button><button type="button" className="secondary" disabled={saving} onClick={()=>void saveOrder('rascunho')}>Salvar rascunho</button><button type="button" className="secondary" onClick={clearForm}>Cancelar</button></div></section>}
  <div className="order-metrics"><article><span className="order-metric-icon"><ShoppingBag size={20}/></span><div><small>Pedidos encontrados</small><strong>{visible.length}</strong></div></article><article><span className="order-metric-icon warning"><UserRoundCheck size={20}/></span><div><small>Aguardando aprovação</small><strong>{approvalCount}</strong></div></article><article><span className="order-metric-icon pricing"><Clock3 size={20}/></span><div><small>Em precificação</small><strong>{pricingCount}</strong></div></article></div>
  <section className="panel orders-panel"><div className="orders-title"><div><h2>Lista de pedidos</h2><p className="muted">Acompanhe pedidos, precificação e aprovação.</p></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/> Atualizar</button></div>{message&&!formOpen&&<output className="notice">{message}</output>}<div className="order-filters"><label><span>Pesquisar</span><span className="order-input-wrap"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Número, cliente ou produto"/></span></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{administrator&&<label>Vendedor<select value={sellerFilter} onChange={e=>setSellerFilter(e.target.value)}><option value="todos">Todos</option>{sellerNames.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}<label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="todos">Todo período</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label>{hasFilters&&<button className="secondary clear-order-filters" onClick={()=>{setQuery('');setStatus('todos');setSellerFilter('todos');setPeriod('todos')}}><FilterX size={16}/> Limpar</button>}</div>
   {error&&<p className="global-alert">{error}</p>}{loading?<div className="orders-empty">Carregando…</div>:visible.length===0?<div className="orders-empty"><ShoppingBag size={30}/><h3>Nenhum pedido encontrado</h3></div>:<ul className="order-list">{visible.map(order=><li className="order-row" key={order.id}><div className="order-main"><strong>{orderNumber(order.numero)}</strong><span>{order.cliente_nome}</span><small>{order.items.map(i=>i.produto_nome).join(', ')}</small>{order.items.some(i=>i.tipo==='novo_produto')&&<em className="new-product-chip">Produto novo</em>}</div><div className="order-field"><small>Vendedor</small><strong>{order.vendedor_nome}</strong></div><div className="order-field"><small>Data</small><strong>{formatDate(order.data_pedido)}</strong></div><div className="order-field"><small>Prazo</small><strong><CalendarDays size={14}/>{formatDate(order.prazo_solicitado)}</strong></div><div className="order-field order-value"><small>Total</small><strong>{reais.format(order.valor_total)}</strong></div><span className={`order-status status-${order.status}`}>{statusLabels[order.status]}</span>{order.items.some(i=>i.foto_urls?.length||i.link_referencia)&&<div className="order-references">{order.items.flatMap(i=>i.foto_urls||[]).slice(0,3).map((url,index)=><img key={url} src={url} alt={`Referência ${index+1}`}/>)}{order.items.find(i=>i.link_referencia)?.link_referencia&&<a href={order.items.find(i=>i.link_referencia)?.link_referencia||''} target="_blank" rel="noreferrer">Abrir referência <ExternalLink size={13}/></a>}</div>}<div className="order-row-actions">{canEdit(order)&&<button className="secondary" onClick={()=>startEdit(order)}><Pencil size={14}/> Alterar</button>}{administrator&&order.status==='aguardando_aprovacao'&&<><button disabled={deciding===order.id} onClick={()=>void approve(order)}><CheckCircle2 size={14}/> Aprovar</button><button className="secondary" onClick={()=>void decide(order,'devolvido_ajuste')}><RotateCcw size={14}/> Solicitar ajuste</button><button className="cancel-order-button" onClick={()=>void decide(order,'reprovado')}><XCircle size={14}/> Reprovar</button></>}{canCancel(order)&&<button className="cancel-order-button" onClick={()=>void cancelOrder(order)}><XCircle size={14}/> Cancelar</button>}</div>{order.decisao_observacao&&<p className="decision-note"><strong>Decisão:</strong> {order.decisao_observacao}</p>}</li>)}</ul>}</section>
 </section>;
}
