'use client';
import {useEffect,useMemo,useState} from 'react';
import {Download,Eye,EyeOff,Image as ImageIcon,Plus,Search,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import './portfolio.css';

type PortfolioProduct={airtable_record_id:string;nome:string;categoria:string|null;preco_venda:number|null;tempo_producao_h:number|null;estoque:number|null;foto_urls:string[];exibir_portfolio:boolean};
type ProductForm={nome:string;categoria:string;preco_venda:string;tempo_producao_h:string;estoque:string;exibir_portfolio:boolean};
const emptyForm:ProductForm={nome:'',categoria:'',preco_venda:'',tempo_producao_h:'',estoque:'',exibir_portfolio:true};
const reais=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const numberOrNull=(value:string)=>value.trim()===''?null:Number(value.replace(',','.'));

export default function Portfolio({administrator}:{administrator:boolean}){
 const [products,setProducts]=useState<PortfolioProduct[]>([]),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[stockFilter,setStockFilter]=useState('todos'),[showHidden,setShowHidden]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState<ProductForm>(emptyForm),[photo,setPhoto]=useState<File|null>(null),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);setError('');let request=supabase.from('farm_portfolio_products').select('airtable_record_id,nome,categoria,preco_venda,tempo_producao_h,estoque,foto_urls,exibir_portfolio').eq('ativo',true).order('nome');if(!administrator)request=request.eq('exibir_portfolio',true);const {data,error}=await request;if(error){setError('Não foi possível carregar o portfólio. Tente novamente.');setProducts([])}else setProducts((data||[]) as PortfolioProduct[]);setLoading(false)}
 useEffect(()=>{void load()},[administrator]);
 const categories=useMemo(()=>['Todos',...Array.from(new Set(products.map(p=>p.categoria).filter(Boolean) as string[])).sort()],[products]);
 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR');return products.filter(product=>{const matchesVisibility=!administrator||showHidden||product.exibir_portfolio;const matchesCategory=category==='Todos'||product.categoria===category;const matchesStock=stockFilter==='todos'||(stockFilter==='com'&&product.estoque!==null&&product.estoque>0)||(stockFilter==='sem'&&product.estoque===0)||(stockFilter==='nao_informado'&&product.estoque===null);const searchable=`${product.nome} ${product.categoria||''}`.toLocaleLowerCase('pt-BR');return matchesVisibility&&matchesCategory&&matchesStock&&(!term||searchable.includes(term))})},[products,query,category,stockFilter,administrator,showHidden]);

 async function createProduct(event:React.FormEvent){event.preventDefault();setMessage('');setSaving(true);const id=`farm_${crypto.randomUUID()}`;let uploadedPath:string|null=null;try{let foto_urls:string[]=[];if(photo){const extension=(photo.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();uploadedPath=`${id}/${Date.now()}.${extension||'jpg'}`;const {error}=await supabase.storage.from('portfolio').upload(uploadedPath,photo,{contentType:photo.type||undefined,upsert:false});if(error)throw error;foto_urls=[supabase.storage.from('portfolio').getPublicUrl(uploadedPath).data.publicUrl]}const {error}=await supabase.from('farm_portfolio_products').insert({airtable_record_id:id,nome:form.nome.trim(),categoria:form.categoria.trim()||null,preco_venda:numberOrNull(form.preco_venda),tempo_producao_h:numberOrNull(form.tempo_producao_h),estoque:numberOrNull(form.estoque),ativo:true,exibir_portfolio:form.exibir_portfolio,foto_urls});if(error)throw error;setForm(emptyForm);setPhoto(null);setFormOpen(false);setMessage(form.exibir_portfolio?'Produto criado e publicado no portfólio.':'Produto criado e mantido oculto no portfólio.');await load()}catch{if(uploadedPath)await supabase.storage.from('portfolio').remove([uploadedPath]);setMessage('Não foi possível cadastrar o produto. Confira os dados e tente novamente.')}finally{setSaving(false)}}
 async function setVisibility(product:PortfolioProduct){setMessage('');const next=!product.exibir_portfolio;const {error}=await supabase.from('farm_portfolio_products').update({exibir_portfolio:next,atualizado_em:new Date().toISOString()}).eq('airtable_record_id',product.airtable_record_id);if(error)setMessage('Não foi possível alterar a visibilidade do produto.');else{setProducts(current=>current.map(item=>item.airtable_record_id===product.airtable_record_id?{...item,exibir_portfolio:next}:item));setMessage(next?'Produto publicado no portfólio.':'Produto ocultado do portfólio.')}}
 function exportPdf(){
  if(visible.length===0){setMessage('Não há produtos nos filtros atuais para exportar.');return}
  const popup=window.open('','_blank');
  if(!popup){setMessage('O navegador bloqueou a janela do PDF. Permita pop-ups e tente novamente.');return}
  popup.opener=null;
  const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));
  const stockLabel=stockFilter==='com'?'Com estoque':stockFilter==='sem'?'Sem estoque':stockFilter==='nao_informado'?'Estoque não informado':'Todos';
  const cards=visible.map(product=>`<article>${product.foto_urls?.[0]?`<img src="${escape(product.foto_urls[0])}" alt="">`:'<div class="placeholder">Sem foto</div>'}<div class="content"><small>${escape(product.categoria||'Sem categoria')}</small><h2>${escape(product.nome)}</h2><p><b>${product.preco_venda!==null?escape(reais.format(product.preco_venda)):'Preço não informado'}</b><span>${product.estoque===null?'Estoque não informado':product.estoque+' em estoque'}</span></p></div></article>`).join('');
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Portfólio - Sonho em Camadas 3D</title><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172a39;margin:0}header{border-bottom:2px solid #b58a2a;padding-bottom:12px;margin-bottom:16px}h1{font-size:24px;margin:0 0 6px}header p{font-size:11px;color:#566573;margin:3px 0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}article{border:1px solid #dce3e9;border-radius:8px;overflow:hidden;break-inside:avoid;display:grid;grid-template-columns:105px 1fr;min-height:120px}article img,.placeholder{width:105px;height:100%;min-height:120px;object-fit:cover;background:#edf1f4}.placeholder{display:grid;place-items:center;color:#71838e;font-size:11px}.content{padding:12px}.content small{color:#126454;font-weight:bold}.content h2{font-size:15px;margin:8px 0 14px}.content p{display:flex;justify-content:space-between;gap:8px;align-items:end;margin:0;font-size:11px}.content b{font-size:15px;color:#126454}.content span{text-align:right;color:#566573}footer{font-size:10px;color:#71838e;margin-top:14px;text-align:right}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><header><h1>Portfólio · Sonho em Camadas 3D</h1><p>Pesquisa: ${escape(query||'Todas')} · Tipo: ${escape(category)} · Estoque: ${stockLabel}</p><p>${visible.length} produto${visible.length===1?'':'s'} · Gerado em ${new Date().toLocaleString('pt-BR')}</p></header><main class="grid">${cards}</main><footer>Sonho em Camadas 3D · Gestão da Farm</footer><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),700))<\/script></body></html>`);
  popup.document.close();setMessage('Documento preparado. Escolha “Salvar como PDF” na janela de impressão.');
 }

 return <section aria-label="Portfólio de produtos">
  {administrator&&<div className="portfolio-admin-actions"><button onClick={()=>setFormOpen(!formOpen)}>{formOpen?<X size={17}/>:<Plus size={17}/>} {formOpen?'Fechar cadastro':'Cadastrar produto'}</button><label className="visibility-filter"><input type="checkbox" checked={showHidden} onChange={event=>setShowHidden(event.target.checked)}/> Mostrar produtos ocultos</label></div>}
  {administrator&&formOpen&&<form className="panel portfolio-form" onSubmit={createProduct}><div className="section-title"><div><h2>Novo produto</h2><p className="muted">Cadastre o produto e escolha se ele aparecerá no portfólio.</p></div></div><div className="fields"><label>Nome<input value={form.nome} onChange={event=>setForm({...form,nome:event.target.value})} required maxLength={160}/></label><label>Categoria<input value={form.categoria} onChange={event=>setForm({...form,categoria:event.target.value})} maxLength={100}/></label><label>Preço de venda (R$)<input inputMode="decimal" value={form.preco_venda} onChange={event=>setForm({...form,preco_venda:event.target.value})} placeholder="0,00"/></label><label>Tempo de produção (h)<input inputMode="decimal" value={form.tempo_producao_h} onChange={event=>setForm({...form,tempo_producao_h:event.target.value})} placeholder="0,00"/></label><label>Estoque<input inputMode="numeric" value={form.estoque} onChange={event=>setForm({...form,estoque:event.target.value})} placeholder="0"/></label><label>Foto do produto<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={event=>setPhoto(event.target.files?.[0]||null)}/></label></div><fieldset className="portfolio-choice"><legend>Exibir no portfólio?</legend><label><input type="radio" name="portfolio" checked={form.exibir_portfolio} onChange={()=>setForm({...form,exibir_portfolio:true})}/> Sim</label><label><input type="radio" name="portfolio" checked={!form.exibir_portfolio} onChange={()=>setForm({...form,exibir_portfolio:false})}/> Não</label></fieldset><button disabled={saving}>{saving?'Salvando…':'Salvar produto'}</button></form>}
  <p className="notice" role="status">{message}</p>
  <div className="portfolio-toolbar"><div className="portfolio-filter-row"><label className="portfolio-search"><Search size={18}/><span className="sr-only">Pesquisar produtos</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar produto"/></label><label className="stock-filter">Estoque<select value={stockFilter} onChange={event=>setStockFilter(event.target.value)}><option value="todos">Todos</option><option value="com">Com estoque</option><option value="sem">Sem estoque</option><option value="nao_informado">Não informado</option></select></label><button className="secondary export-button" onClick={exportPdf}><Download size={17}/> Exportar PDF</button></div><div><p className="filter-label">Tipo de produto</p><div className="category-list" aria-label="Filtrar por tipo de produto">{categories.map(item=><button key={item} className={category===item?'category active':'category'} onClick={()=>setCategory(item)}>{item}</button>)}</div></div></div>
  {loading?<div className="panel portfolio-state" role="status">Carregando produtos do portfólio…</div>:error?<div className="panel portfolio-state" role="alert">{error}</div>:<><p className="portfolio-count">{visible.length} {visible.length===1?'produto':'produtos'} encontrado{visible.length===1?'':'s'}</p>{visible.length===0?<div className="panel portfolio-state"><Search size={28}/><h2>Nenhum produto encontrado</h2><p>Altere a pesquisa ou escolha outra categoria.</p></div>:<div className="portfolio-grid">{visible.map(product=><article className={product.exibir_portfolio?'portfolio-card':'portfolio-card hidden-product'} key={product.airtable_record_id}><div className="portfolio-image">{product.foto_urls?.[0]?<img src={product.foto_urls[0]} alt={`Foto de ${product.nome}`} loading="lazy"/>:<div className="portfolio-placeholder"><ImageIcon size={34}/><span>Foto ainda não cadastrada</span></div>}</div><div className="portfolio-card-body"><div className="portfolio-card-top"><span className="badge">{product.categoria||'Sem categoria'}</span>{product.estoque!==null&&<small>{product.estoque} em estoque</small>}</div><h2>{product.nome}</h2><div className="portfolio-meta">{product.preco_venda!==null&&<strong>{reais.format(product.preco_venda)}</strong>}{product.tempo_producao_h!==null&&<span>{product.tempo_producao_h.toLocaleString('pt-BR')} h de produção</span>}</div>{administrator&&<button className="secondary visibility-button" onClick={()=>void setVisibility(product)}>{product.exibir_portfolio?<><EyeOff size={16}/> Ocultar do portfólio</>:<><Eye size={16}/> Publicar no portfólio</>}</button>}</div></article>)}</div>}</>}
 </section>
}
