'use client';
/* oxlint-disable next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Clock3,Columns3,ExternalLink,Factory,FilterX,ImageIcon,List,MonitorUp,PackageCheck,Pencil,Plus,RefreshCw,Search,Trash2,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Dialog,DialogClose,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import './production.css';
import './production-enhancements.css';

type ProductionStatus='analise_produto'|'aguardando_producao'|'em_impressao'|'acabamento'|'pronto'|'cancelado';
type ProductionView='kanban'|'list';
type ProductOrigin='novo'|'portfolio';
type ProductionPlate={numero:number;quantidade:number;horas:number;minutos:number;insumo_gramas:number;concluida:boolean};
type ProductionOrder={id:string;pedido_id:string|null;produto_id:string|null;produto_nome:string;quantidade:number;status:ProductionStatus;detalhes:string|null;link_referencia:string|null;foto_urls:string[];mesas:ProductionPlate[];data_prevista_entrega:string|null;origem_produto:ProductOrigin;criar_no_portfolio:boolean;estoque_lancado_em:string|null;produto_portfolio_criado_id:string|null;criado_em:string;pedido:{numero:number;cliente_nome:string}|null};
type RawProduction=Omit<ProductionOrder,'pedido'|'mesas'>&{mesas:unknown;pedido:{numero:number;cliente_nome:string}|{numero:number;cliente_nome:string}[]|null};
type PortfolioProduct={airtable_record_id:string;nome:string;categoria:string|null;estoque:number|null;observacoes:string|null;link_produto:string|null;foto_urls:string[]};
type ProductionForm={origem_produto:ProductOrigin;produto_id:string;produto_nome:string;quantidade:string;status:ProductionStatus;detalhes:string;link_referencia:string;mesas:ProductionPlate[];data_prevista_entrega:string;criar_no_portfolio:boolean};

const environment=import.meta.env.BASE_URL.includes('/desenvolvimento/')?'desenvolvimento':'producao';
const labels:Record<ProductionStatus,string>={analise_produto:'Análise do produto',aguardando_producao:'Aguardando produção',em_impressao:'Em impressão',acabamento:'Acabamento',pronto:'Pronto',cancelado:'Cancelado'};
const statusOrder:ProductionStatus[]=['analise_produto','aguardando_producao','em_impressao','acabamento','pronto','cancelado'];
const next:Partial<Record<ProductionStatus,[ProductionStatus,string]>>={analise_produto:['aguardando_producao','Concluir análise'],aguardando_producao:['em_impressao','Iniciar impressão'],em_impressao:['acabamento','Enviar para acabamento'],acabamento:['pronto','Finalizar produção']};
const blankPlate=(numero:number,quantidade=0):ProductionPlate=>({numero,quantidade,horas:0,minutos:0,insumo_gramas:0,concluida:false});
const emptyForm:ProductionForm={origem_produto:'portfolio',produto_id:'',produto_nome:'',quantidade:'1',status:'analise_produto',detalhes:'',link_referencia:'',mesas:[blankPlate(1,1)],data_prevista_entrega:'',criar_no_portfolio:false};
const orderNumber=(value:number)=>`#${String(value).padStart(4,'0')}`;
const orderStoragePath=(url:string)=>{const marker='/storage/v1/object/public/orders/';const index=url.indexOf(marker);return index>=0?decodeURIComponent(url.slice(index+marker.length)):null};
const normalizePlates=(value:unknown):ProductionPlate[]=>Array.isArray(value)?value.map((entry,index)=>{const plate=entry&&typeof entry==='object'?entry as Partial<ProductionPlate>:{};return{numero:index+1,quantidade:Math.max(0,Math.floor(Number(plate.quantidade)||0)),horas:Math.max(0,Math.floor(Number(plate.horas)||0)),minutos:Math.min(59,Math.max(0,Math.floor(Number(plate.minutos)||0))),insumo_gramas:Math.max(0,Number(plate.insumo_gramas)||0),concluida:Boolean(plate.concluida)}}):[];
const plateDuration=(plate:ProductionPlate)=>`${plate.horas}h ${String(plate.minutos).padStart(2,'0')}min`;
const plateQuantity=(plates:ProductionPlate[])=>plates.reduce((total,plate)=>total+plate.quantidade,0);
const platesCompleted=(plates:ProductionPlate[])=>plates.length>0&&plates.every(plate=>plate.concluida);
const deliveryDate=(value:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T00:00:00`));

export default function Production({administrator,userId,boardOnly=false}:{administrator:boolean;userId:string;boardOnly?:boolean}){
 const viewKey=`farm.productionView.${environment}`;
 const draftKey=`farm.productionDraft.${environment}.${userId}`;
 const [items,setItems]=useState<ProductionOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'todos'|ProductionStatus>('todos'),[updating,setUpdating]=useState<string|null>(null),[view,setView]=useState<ProductionView>('kanban');
 const [portfolioProducts,setPortfolioProducts]=useState<PortfolioProduct[]>([]);
 const [dialogOpen,setDialogOpen]=useState(false),[editing,setEditing]=useState<ProductionOrder|null>(null),[form,setForm]=useState<ProductionForm>(emptyForm),[photo,setPhoto]=useState<File|null>(null),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[draftRestored,setDraftRestored]=useState(false);

 const load=useCallback(async()=>{setLoading(true);setError('');const [productionResult,productsResult]=await Promise.all([supabase.from('farm_production_orders').select('id,pedido_id,produto_id,produto_nome,quantidade,status,detalhes,link_referencia,foto_urls,mesas,data_prevista_entrega,origem_produto,criar_no_portfolio,estoque_lancado_em,produto_portfolio_criado_id,criado_em,pedido:farm_orders(numero,cliente_nome)').eq('ambiente',environment).order('criado_em',{ascending:false}),supabase.from('farm_portfolio_products').select('airtable_record_id,nome,categoria,estoque,observacoes,link_produto,foto_urls').eq('ativo',true).is('excluido_em',null).order('nome')]);if(productionResult.error||productsResult.error){setError('Não foi possível carregar as ordens de produção.');setItems([])}else{setItems(((productionResult.data||[]) as unknown as RawProduction[]).map(item=>({...item,quantidade:Number(item.quantidade),mesas:normalizePlates(item.mesas),pedido:Array.isArray(item.pedido)?item.pedido[0]||null:item.pedido})));setPortfolioProducts(((productsResult.data||[]) as PortfolioProduct[]).map(item=>({...item,estoque:item.estoque===null?null:Number(item.estoque)})))}setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{if(!boardOnly)return;const interval=window.setInterval(()=>{void load()},30000);return()=>window.clearInterval(interval)},[boardOnly,load]);
 useEffect(()=>{const timer=window.setTimeout(()=>{if(boardOnly){setView('kanban');setDraftRestored(true);return}const saved=sessionStorage.getItem(viewKey);if(saved==='kanban'||saved==='list')setView(saved);try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null') as {open?:boolean;form?:Partial<ProductionForm>}|null;if(draft?.open){const restored={...emptyForm,...draft.form};setForm({...restored,mesas:normalizePlates(restored.mesas).length?normalizePlates(restored.mesas):[blankPlate(1,Math.max(1,Math.floor(Number(restored.quantidade))||1))]});setDialogOpen(true);setMessage('Rascunho do novo card recuperado. Se havia uma foto, escolha o arquivo novamente.')}}catch{sessionStorage.removeItem(draftKey)}setDraftRestored(true)},0);return()=>window.clearTimeout(timer)},[boardOnly,draftKey,viewKey]);
 useEffect(()=>{if(!draftRestored||editing)return;if(dialogOpen)sessionStorage.setItem(draftKey,JSON.stringify({open:true,form}));else sessionStorage.removeItem(draftKey)},[dialogOpen,draftKey,draftRestored,editing,form]);

 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR');return items.filter(item=>(status==='todos'||item.status===status)&&(!term||[item.produto_nome,item.pedido?.cliente_nome,item.pedido?.numero].join(' ').toLocaleLowerCase('pt-BR').includes(term)))},[items,query,status]);
 const analysis=items.filter(item=>item.status==='analise_produto').length,inProgress=items.filter(item=>['aguardando_producao','em_impressao','acabamento'].includes(item.status)).length,ready=items.filter(item=>item.status==='pronto').length;

 function changeView(nextView:ProductionView){setView(nextView);sessionStorage.setItem(viewKey,nextView)}
 function openWallboard(){const url=new URL(window.location.href);url.searchParams.set('gestao-a-vista','1');window.open(url.href,'_blank','noopener,noreferrer')}
 function openCreate(){setEditing(null);setForm({...emptyForm,mesas:[blankPlate(1,1)]});setPhoto(null);setMessage('');setDialogOpen(true)}
 function openEdit(item:ProductionOrder){setEditing(item);setForm({origem_produto:item.origem_produto||'novo',produto_id:item.produto_id||'',produto_nome:item.produto_nome,quantidade:String(item.quantidade),status:item.status,detalhes:item.detalhes||'',link_referencia:item.link_referencia||'',mesas:item.mesas.length?item.mesas:[blankPlate(1,item.quantidade)],data_prevista_entrega:item.data_prevista_entrega||'',criar_no_portfolio:item.criar_no_portfolio});setPhoto(null);setMessage('');setDialogOpen(true)}
 function closeDialog(){setDialogOpen(false);setEditing(null);setForm(emptyForm);setPhoto(null);sessionStorage.removeItem(draftKey)}
 function selectPortfolioProduct(productId:string){const product=portfolioProducts.find(item=>item.airtable_record_id===productId);setForm(current=>({...current,produto_id:productId,produto_nome:product?.nome||'',detalhes:product?.observacoes||'',link_referencia:product?.link_produto||'',criar_no_portfolio:false}))}
 function changePlateCount(value:number){const count=Math.min(30,Math.max(1,Math.floor(value)||1));setForm(current=>({...current,mesas:Array.from({length:count},(_,index)=>current.mesas[index]?{...current.mesas[index],numero:index+1}:blankPlate(index+1))}))}
 function updatePlate(index:number,changes:Partial<ProductionPlate>){setForm(current=>({...current,mesas:current.mesas.map((plate,plateIndex)=>plateIndex===index?{...plate,...changes,numero:plateIndex+1}:plate)}))}
 function changeTotalQuantity(value:string){setForm(current=>{const previous=Math.max(1,Math.floor(Number(current.quantidade))||1),nextQuantity=Math.max(1,Math.floor(Number(value))||1);return{...current,quantidade:value,mesas:current.mesas.length===1&&current.mesas[0].quantidade===previous?[{...current.mesas[0],quantidade:nextQuantity}]:current.mesas}})}

 async function syncParentOrder(orderId:string|null){if(!orderId)return;const {data:siblings}=await supabase.from('farm_production_orders').select('status').eq('pedido_id',orderId);if(!siblings?.length)return;const completed=siblings.every(row=>row.status==='pronto'||row.status==='cancelado');const {data:order}=await supabase.from('farm_orders').select('status').eq('id',orderId).maybeSingle();if(order&&['cancelado','reprovado','entregue'].includes(order.status))return;await supabase.from('farm_orders').update({status:completed?'pronto':'em_producao',atualizado_em:new Date().toISOString()}).eq('id',orderId)}

 async function saveCard(event:React.SyntheticEvent<HTMLFormElement>){
  event.preventDefault();
  const quantity=Math.floor(Number(form.quantidade)),mesas=normalizePlates(form.mesas);
  if(!form.produto_nome.trim()||!Number.isFinite(quantity)||quantity<1){setMessage('Informe o produto e uma quantidade válida.');return}
  if(!editing&&form.origem_produto==='portfolio'&&!form.produto_id){setMessage('Selecione um produto do Portfólio.');return}
  if(mesas.length<1){setMessage('Informe pelo menos uma mesa de impressão.');return}
  if(plateQuantity(mesas)!==quantity){setMessage(`A soma das quantidades das mesas deve ser ${quantity}. Total informado: ${plateQuantity(mesas)}.`);return}
  if(['acabamento','pronto'].includes(form.status)&&!platesCompleted(mesas)){setMessage('Conclua todas as mesas antes de enviar o card para Acabamento.');return}
  setSaving(true);setMessage('');let uploadedPath:string|null=null;
  try{
   const selectedProduct=portfolioProducts.find(item=>item.airtable_record_id===form.produto_id);
   let foto_urls=editing?.foto_urls||(form.origem_produto==='portfolio'?selectedProduct?.foto_urls||[]:[]);
   if(photo){const extension=(photo.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();uploadedPath=`${userId}/production/${editing?.id||crypto.randomUUID()}/${crypto.randomUUID()}.${extension||'jpg'}`;const upload=await supabase.storage.from('orders').upload(uploadedPath,photo,{contentType:photo.type||undefined,upsert:false});if(upload.error)throw upload.error;foto_urls=[supabase.storage.from('orders').getPublicUrl(uploadedPath).data.publicUrl,...foto_urls]}
   const values={produto_id:form.origem_produto==='portfolio'?form.produto_id:null,produto_nome:form.produto_nome.trim(),origem_produto:form.origem_produto,criar_no_portfolio:form.origem_produto==='novo'&&form.criar_no_portfolio,quantidade:quantity,status:form.status,detalhes:form.detalhes.trim()||null,link_referencia:form.link_referencia.trim()||null,foto_urls,mesas,data_prevista_entrega:form.data_prevista_entrega||null,atualizado_em:new Date().toISOString()};
   if(editing){const {error:updateError}=await supabase.from('farm_production_orders').update(values).eq('id',editing.id);if(updateError)throw updateError;await syncParentOrder(editing.pedido_id)}
   else{const {error:insertError}=await supabase.from('farm_production_orders').insert({...values,pedido_id:null,item_pedido_id:null,ambiente:environment});if(insertError)throw insertError}
   closeDialog();setMessage(editing?'Card de produção atualizado.':'Novo card adicionado à produção.');await load();
  }catch(error){if(uploadedPath)await supabase.storage.from('orders').remove([uploadedPath]);setMessage(error instanceof Error?error.message:'Não foi possível salvar o card. Confira os dados e tente novamente.')}finally{setSaving(false)}
 }

 async function advance(item:ProductionOrder){const action=next[item.status];if(!action)return;const [newStatus,label]=action;if(newStatus==='acabamento'){if(plateQuantity(item.mesas)!==item.quantidade){setMessage(`Distribua as ${item.quantidade} unidades entre as mesas antes de enviar para Acabamento.`);return}if(!platesCompleted(item.mesas)){setMessage('Conclua todas as mesas antes de enviar o card para Acabamento.');return}}setUpdating(item.id);setMessage('');const {error:updateError}=await supabase.from('farm_production_orders').update({status:newStatus,atualizado_em:new Date().toISOString()}).eq('id',item.id);if(updateError)setMessage(updateError.message||'Não foi possível atualizar a produção.');else{await syncParentOrder(item.pedido_id);const stockMessage=newStatus==='pronto'&&!item.pedido_id?(item.origem_produto==='portfolio'?' A quantidade produzida foi adicionada ao estoque.':item.criar_no_portfolio?' O produto foi criado como oculto no Portfólio e adicionado ao estoque.':' O produto não foi enviado ao Portfólio nem ao estoque.'):' ';setMessage(`${item.produto_nome}: ${label.toLocaleLowerCase('pt-BR')} registrado.${stockMessage}`);await load()}setUpdating(null)}
 async function togglePlate(item:ProductionOrder,index:number){const mesas=item.mesas.map((plate,plateIndex)=>plateIndex===index?{...plate,concluida:!plate.concluida}:plate);setUpdating(`${item.id}:mesa:${index}`);setMessage('');const {error:updateError}=await supabase.from('farm_production_orders').update({mesas,atualizado_em:new Date().toISOString()}).eq('id',item.id);if(updateError)setMessage(`Não foi possível atualizar a Mesa ${index+1}.`);else{setItems(current=>current.map(row=>row.id===item.id?{...row,mesas}:row));setMessage(`Mesa ${index+1} ${mesas[index].concluida?'concluída':'reaberta'}.`)}setUpdating(null)}
 async function deleteCard(item:ProductionOrder){
  if(!administrator||item.pedido_id){setMessage('Cards vinculados a pedidos devem ser cancelados para preservar o histórico.');return}
  if(!window.confirm(`Excluir permanentemente o card manual “${item.produto_nome}”? Esta ação não pode ser desfeita.`))return;
  setDeleting(true);setMessage('');
  const {data,error:deleteError}=await supabase.from('farm_production_orders').delete().eq('id',item.id).is('pedido_id',null).select('id').maybeSingle();
  if(deleteError||!data){setMessage('Não foi possível excluir o card. Atualize a página e tente novamente.');setDeleting(false);return}
  const paths=item.foto_urls.map(orderStoragePath).filter((path):path is string=>Boolean(path));
  if(paths.length)await supabase.storage.from('orders').remove(paths);
  closeDialog();setMessage('Card manual excluído permanentemente.');await load();setDeleting(false);
 }
 function renderCard(item:ProductionOrder,kanban=false,readOnly=false){return <li key={item.id} className={`production-card${kanban?' production-kanban-card':''}${readOnly?' production-readonly-card':''}`}>
  {!readOnly&&<button type="button" className="production-card-hit" aria-label={`${item.produto_nome}. Clique duas vezes para alterar.`} onDoubleClick={()=>openEdit(item)}><span className="sr-only">Clique duas vezes para abrir e alterar {item.produto_nome}</span></button>}
  {item.foto_urls?.[0]?<img src={item.foto_urls[0]} alt={`Referência de ${item.produto_nome}`}/>:<span className="production-placeholder"><ImageIcon size={25}/></span>}
  <div className="production-main"><small>{item.pedido?`${orderNumber(item.pedido.numero)} · ${item.pedido.cliente_nome}`:'Produção manual'}</small><strong>{item.produto_nome}</strong><span>{item.quantidade} {item.quantidade===1?'unidade':'unidades'}</span>{!item.pedido_id&&<span className="production-source">{item.origem_produto==='portfolio'?'Produto do Portfólio':item.criar_no_portfolio?'Produto novo · criar no Portfólio':'Produto novo · não criar no Portfólio'}{item.estoque_lancado_em?' · estoque atualizado':''}</span>}{item.data_prevista_entrega&&<span className="production-delivery">Entrega prevista: {deliveryDate(item.data_prevista_entrega)}</span>}{item.detalhes&&<p>{item.detalhes}</p>}</div>
  <span className={`production-status production-${item.status}`}>{labels[item.status]}</span>
  <div className="production-plates"><div className="production-plates-title"><strong>Mesas de impressão</strong><span>{item.mesas.length}</span></div>{item.mesas.length?<ul>{item.mesas.map((plate,index)=><li key={plate.numero} className={plate.concluida?'completed':''}><label><input type="checkbox" checked={plate.concluida} disabled={readOnly||updating===`${item.id}:mesa:${index}`} onChange={()=>void togglePlate(item,index)}/><span>Mesa {plate.numero} · {plate.quantidade} {plate.quantidade===1?'unidade':'unidades'}</span></label><small>Horas: {plateDuration(plate)} · Custo de insumo: {plate.insumo_gramas.toLocaleString('pt-BR')} g</small></li>)}</ul>:<small className="production-no-plates">Nenhuma mesa informada.</small>}</div>
  {!readOnly&&<div className="production-actions">{item.link_referencia&&<a className="secondary" href={item.link_referencia} target="_blank" rel="noreferrer">Abrir link <ExternalLink size={14}/></a>}<button className="secondary" onClick={()=>openEdit(item)}><Pencil size={14}/> Abrir e alterar</button>{next[item.status]&&<button disabled={updating===item.id} onClick={()=>void advance(item)}>{updating===item.id?'Atualizando…':<><CheckCircle2 size={15}/>{next[item.status]?.[1]}</>}</button>}</div>}
 </li>}

 if(boardOnly)return <main className="production-wallboard"><header className="production-wallboard-header"><div><img src="brand/Logo_Otimizada_Preta.png" alt="Sonho em Camadas 3D"/><span><small>PRODUÇÃO</small><strong>Gestão à vista</strong></span></div><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'Atualizando…':'Atualizar'}</button></header>{error&&<p className="global-alert" role="alert">{error}</p>}{loading?<div className="orders-empty">Carregando produção…</div>:<div className="production-board production-wallboard-board" aria-label="Kanban da produção">{statusOrder.map(columnStatus=>{const columnItems=items.filter(item=>item.status===columnStatus);return <section className={`production-column production-column-${columnStatus}`} key={columnStatus}><header><h3>{labels[columnStatus]}</h3><span>{columnItems.length}</span></header>{columnItems.length?<ul>{columnItems.map(item=>renderCard(item,true,true))}</ul>:<p className="production-column-empty">Nenhuma ordem nesta etapa.</p>}</section>})}</div>}</main>;

 return <section className="production-module" aria-label="Fluxo de produção">
  <div className="production-metrics"><article><span><Clock3 size={20}/></span><div><small>Em análise</small><strong>{analysis}</strong></div></article><article><span><Factory size={20}/></span><div><small>Em produção</small><strong>{inProgress}</strong></div></article><article><span><PackageCheck size={20}/></span><div><small>Prontos</small><strong>{ready}</strong></div></article></div>
  <section className="panel production-panel"><div className="orders-title"><div><h2>Ordens de produção</h2><p className="muted">Pedidos sem estoque começam pela análise do produto. Também é possível incluir um card manualmente.</p></div><div className="production-heading-actions"><button onClick={openCreate}><Plus size={16}/> Novo card</button><button className="secondary" onClick={openWallboard}><MonitorUp size={16}/> Gestão à vista</button><fieldset className="production-view-toggle" aria-label="Visualização da produção"><button type="button" className={view==='kanban'?'active':''} aria-pressed={view==='kanban'} onClick={()=>changeView('kanban')}><Columns3 size={16}/> Kanban</button><button type="button" className={view==='list'?'active':''} aria-pressed={view==='list'} onClick={()=>changeView('list')}><List size={16}/> Lista</button></fieldset><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'Atualizando…':'Atualizar'}</button></div></div>
   {message&&<output className="notice">{message}</output>}<div className="production-filters"><label><span>Pesquisar</span><span className="order-input-wrap"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Produto, cliente ou pedido"/></span></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value as 'todos'|ProductionStatus)}><option value="todos">Todos os status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{(query||status!=='todos')&&<button className="secondary" onClick={()=>{setQuery('');setStatus('todos')}}><FilterX size={16}/> Limpar filtros</button>}</div>
   {error&&<p className="global-alert" role="alert">{error}</p>}{loading?<div className="orders-empty">Carregando produção…</div>:view==='kanban'?<div className="production-board" aria-label="Kanban da produção">{statusOrder.filter(columnStatus=>status==='todos'||status===columnStatus).map(columnStatus=>{const columnItems=visible.filter(item=>item.status===columnStatus);return <section className={`production-column production-column-${columnStatus}`} key={columnStatus}><header><h3>{labels[columnStatus]}</h3><span>{columnItems.length}</span></header>{columnItems.length?<ul>{columnItems.map(item=>renderCard(item,true))}</ul>:<p className="production-column-empty">Nenhuma ordem nesta etapa.</p>}</section>})}</div>:visible.length===0?<div className="orders-empty"><Factory size={30}/><h3>Nenhuma ordem encontrada</h3><p>Adicione um novo card ou aprove um pedido que precisa de produção.</p></div>:<ul className="production-list">{visible.map(item=>renderCard(item))}</ul>}
  </section>
  <Dialog open={dialogOpen} onOpenChange={open=>{if(!open&&!deleting)closeDialog()}}><DialogContent className="production-dialog" showCloseButton={false}>
   <DialogClose className="product-dialog-close" aria-label="Fechar" disabled={deleting}><X size={19}/></DialogClose>
   <DialogHeader><DialogTitle>{editing?'Alterar card de produção':'Novo card de produção'}</DialogTitle><DialogDescription>{editing?.pedido?`Este card está vinculado ao pedido ${orderNumber(editing.pedido.numero)}. Para removê-lo do fluxo, altere a etapa para Cancelado.`:'Registre uma demanda manual na esteira de produção.'}</DialogDescription></DialogHeader>
   <form className="production-form" onSubmit={saveCard}><div className="production-form-fields">
    {!editing?.pedido_id&&<fieldset className="production-source-picker wide-field"><legend>O que será produzido?</legend><label><input aria-label="Produto do Portfólio" type="radio" name="origem_produto" value="portfolio" checked={form.origem_produto==='portfolio'} disabled={Boolean(editing?.estoque_lancado_em)} onChange={()=>setForm(current=>({...current,origem_produto:'portfolio',produto_id:'',produto_nome:'',detalhes:'',link_referencia:'',criar_no_portfolio:false}))}/><span><strong>Produto do Portfólio</strong><small>Selecione um produto já cadastrado. Ao finalizar, a quantidade entra no estoque.</small></span></label><label><input aria-label="Produto novo" type="radio" name="origem_produto" value="novo" checked={form.origem_produto==='novo'} disabled={Boolean(editing?.estoque_lancado_em)} onChange={()=>setForm(current=>({...current,origem_produto:'novo',produto_id:'',produto_nome:'',detalhes:'',link_referencia:'',criar_no_portfolio:false}))}/><span><strong>Produto novo</strong><small>Cadastre os dados da nova produção.</small></span></label></fieldset>}
    {editing?.pedido_id?<label>Produto<input value={form.produto_nome} onChange={event=>setForm({...form,produto_nome:event.target.value})} required maxLength={160}/></label>:form.origem_produto==='portfolio'?<label className="wide-field">Selecionar produto do Portfólio<select value={form.produto_id} onChange={event=>selectPortfolioProduct(event.target.value)} required disabled={Boolean(editing?.estoque_lancado_em)}><option value="">Selecione um produto</option>{portfolioProducts.map(product=><option key={product.airtable_record_id} value={product.airtable_record_id}>{product.nome}{product.categoria?` · ${product.categoria}`:''} · {product.estoque||0} em estoque</option>)}</select></label>:<><label className="wide-field">Nome do produto novo<input value={form.produto_nome} onChange={event=>setForm({...form,produto_nome:event.target.value})} required maxLength={160} placeholder="Nome do produto"/></label><label className="production-create-portfolio wide-field"><input aria-label="Criar no Portfólio" type="checkbox" checked={form.criar_no_portfolio} disabled={Boolean(editing?.estoque_lancado_em)} onChange={event=>setForm({...form,criar_no_portfolio:event.target.checked})}/><span><strong>É para criar no Portfólio?</strong><small>Ao finalizar, o produto será criado como oculto, com a quantidade produzida no estoque.</small></span></label></>}
    <label>Quantidade<input type="number" inputMode="numeric" min="1" step="1" value={form.quantidade} onChange={event=>changeTotalQuantity(event.target.value)} disabled={Boolean(editing?.estoque_lancado_em)} required/></label>
    <label>Qtd. de mesas<input type="number" inputMode="numeric" min="1" max="30" step="1" value={form.mesas.length} onChange={event=>changePlateCount(Number(event.target.value))} required/><small className="field-hint">De 1 a 30 mesas por card.</small></label>
    <label>Etapa<select value={form.status} onChange={event=>setForm({...form,status:event.target.value as ProductionStatus})}>{statusOrder.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>
    <label>Data prevista de entrega <small className="optional-label">(opcional)</small><input type="date" value={form.data_prevista_entrega} onChange={event=>setForm({...form,data_prevista_entrega:event.target.value})}/></label>
    <fieldset className="production-plate-editor wide-field"><legend>Detalhes das mesas</legend><div className={`production-plate-total ${plateQuantity(form.mesas)===Math.max(1,Math.floor(Number(form.quantidade))||1)?'valid':'invalid'}`}>Quantidade nas mesas: <strong>{plateQuantity(form.mesas)} de {Math.max(1,Math.floor(Number(form.quantidade))||1)}</strong></div>{form.mesas.map((plate,index)=><article key={plate.numero}><header><strong>Mesa {plate.numero}</strong><label className="production-plate-check"><input type="checkbox" checked={plate.concluida} onChange={event=>updatePlate(index,{concluida:event.target.checked})}/> Concluída</label></header><div><label>Quantidade de produtos<input type="number" inputMode="numeric" min="0" step="1" value={plate.quantidade} onChange={event=>updatePlate(index,{quantidade:Math.max(0,Math.floor(Number(event.target.value)||0))})}/></label><label>Horas<input type="number" inputMode="numeric" min="0" step="1" value={plate.horas} onChange={event=>updatePlate(index,{horas:Math.max(0,Number(event.target.value)||0)})}/></label><label>Minutos<input type="number" inputMode="numeric" min="0" max="59" step="1" value={plate.minutos} onChange={event=>updatePlate(index,{minutos:Math.min(59,Math.max(0,Number(event.target.value)||0))})}/></label><label>Custo de insumo (g)<input type="number" inputMode="decimal" min="0" step="0.01" value={plate.insumo_gramas} onChange={event=>updatePlate(index,{insumo_gramas:Math.max(0,Number(event.target.value)||0)})}/></label></div></article>)}</fieldset>
    <label className="wide-field">Detalhes<textarea value={form.detalhes} onChange={event=>setForm({...form,detalhes:event.target.value})} rows={4} placeholder="Cor, acabamento, medidas ou observações"/></label>
    <label className="wide-field">Link de referência<input type="url" inputMode="url" value={form.link_referencia} onChange={event=>setForm({...form,link_referencia:event.target.value})} placeholder="https://..."/></label>
    <label className="wide-field">Foto<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={event=>setPhoto(event.target.files?.[0]||null)}/><small className="field-hint">{editing?.foto_urls?.length?'Escolha uma imagem somente se quiser adicionar uma nova foto ao card.':'Opcional. A imagem será exibida no card.'}</small></label>
   </div>{message&&<output className="notice">{message}</output>}<div className="form-actions"><button disabled={saving||deleting}>{saving?'Salvando…':editing?'Salvar alterações':'Adicionar card'}</button>{administrator&&editing&&!editing.pedido_id&&<button type="button" className="danger-button" disabled={saving||deleting} onClick={()=>void deleteCard(editing)}><Trash2 size={16}/>{deleting?'Excluindo…':'Excluir card'}</button>}<button type="button" className="secondary" disabled={deleting} onClick={closeDialog}>Cancelar</button></div></form>
  </DialogContent></Dialog>
 </section>;
}
