'use client';
/* oxlint-disable next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Clock3,Columns3,ExternalLink,Factory,FilterX,ImageIcon,List,PackageCheck,RefreshCw,Search} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import './production.css';

type ProductionStatus='analise_produto'|'aguardando_producao'|'em_impressao'|'acabamento'|'pronto'|'cancelado';
type ProductionView='kanban'|'list';
type ProductionOrder={id:string;pedido_id:string;produto_id:string|null;produto_nome:string;quantidade:number;status:ProductionStatus;detalhes:string|null;link_referencia:string|null;foto_urls:string[];criado_em:string;pedido:{numero:number;cliente_nome:string}|null};
type RawProduction=Omit<ProductionOrder,'pedido'>&{pedido:{numero:number;cliente_nome:string}|{numero:number;cliente_nome:string}[]|null};
const environment=import.meta.env.BASE_URL.includes('/desenvolvimento/')?'desenvolvimento':'producao';
const labels:Record<ProductionStatus,string>={analise_produto:'Análise do produto',aguardando_producao:'Aguardando produção',em_impressao:'Em impressão',acabamento:'Acabamento',pronto:'Pronto',cancelado:'Cancelado'};
const statusOrder:ProductionStatus[]=['analise_produto','aguardando_producao','em_impressao','acabamento','pronto','cancelado'];
const next:Partial<Record<ProductionStatus,[ProductionStatus,string]>>={analise_produto:['aguardando_producao','Concluir análise'],aguardando_producao:['em_impressao','Iniciar impressão'],em_impressao:['acabamento','Enviar para acabamento'],acabamento:['pronto','Finalizar produção']};
const orderNumber=(value:number)=>`#${String(value).padStart(4,'0')}`;

export default function Production(){
 const viewKey=`farm.productionView.${environment}`;
 const [items,setItems]=useState<ProductionOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'todos'|ProductionStatus>('todos'),[updating,setUpdating]=useState<string|null>(null),[view,setView]=useState<ProductionView>('kanban');
 const load=useCallback(async()=>{setLoading(true);setError('');const {data,error:loadError}=await supabase.from('farm_production_orders').select('id,pedido_id,produto_id,produto_nome,quantidade,status,detalhes,link_referencia,foto_urls,criado_em,pedido:farm_orders(numero,cliente_nome)').eq('ambiente',environment).order('criado_em',{ascending:false});if(loadError){setError('Não foi possível carregar as ordens de produção.');setItems([])}else setItems(((data||[]) as unknown as RawProduction[]).map(item=>({...item,quantidade:Number(item.quantidade),pedido:Array.isArray(item.pedido)?item.pedido[0]||null:item.pedido})));setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=sessionStorage.getItem(viewKey);if(saved==='kanban'||saved==='list')setView(saved)},0);return()=>window.clearTimeout(timer)},[viewKey]);
 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR');return items.filter(item=>(status==='todos'||item.status===status)&&(!term||[item.produto_nome,item.pedido?.cliente_nome,item.pedido?.numero].join(' ').toLocaleLowerCase('pt-BR').includes(term)))},[items,query,status]);
 const analysis=items.filter(item=>item.status==='analise_produto').length,inProgress=items.filter(item=>['aguardando_producao','em_impressao','acabamento'].includes(item.status)).length,ready=items.filter(item=>item.status==='pronto').length;
 function changeView(nextView:ProductionView){setView(nextView);sessionStorage.setItem(viewKey,nextView)}
 async function advance(item:ProductionOrder){const action=next[item.status];if(!action)return;setUpdating(item.id);setMessage('');const [newStatus,label]=action;const {error:updateError}=await supabase.from('farm_production_orders').update({status:newStatus,atualizado_em:new Date().toISOString()}).eq('id',item.id);if(updateError)setMessage('Não foi possível atualizar a produção.');else{if(newStatus==='pronto'){const {data:siblings}=await supabase.from('farm_production_orders').select('status').eq('pedido_id',item.pedido_id);if((siblings||[]).every(row=>row.status==='pronto'||row.status==='cancelado'))await supabase.from('farm_orders').update({status:'pronto',atualizado_em:new Date().toISOString()}).eq('id',item.pedido_id)}setMessage(`${item.produto_nome}: ${label.toLocaleLowerCase('pt-BR')} registrado.`);await load()}setUpdating(null)}
 function renderCard(item:ProductionOrder,kanban=false){return <li key={item.id} className={`production-card${kanban?' production-kanban-card':''}`}>{item.foto_urls?.[0]?<img src={item.foto_urls[0]} alt={`Referência de ${item.produto_nome}`}/>:<span className="production-placeholder"><ImageIcon size={25}/></span>}<div className="production-main"><small>{item.pedido?`${orderNumber(item.pedido.numero)} · ${item.pedido.cliente_nome}`:'Pedido'}</small><strong>{item.produto_nome}</strong><span>{item.quantidade} {item.quantidade===1?'unidade':'unidades'}</span>{item.detalhes&&<p>{item.detalhes}</p>}</div><span className={`production-status production-${item.status}`}>{labels[item.status]}</span><div className="production-actions">{item.link_referencia&&<a className="secondary" href={item.link_referencia} target="_blank" rel="noreferrer">Abrir link <ExternalLink size={14}/></a>}{next[item.status]&&<button disabled={updating===item.id} onClick={()=>void advance(item)}>{updating===item.id?'Atualizando…':<><CheckCircle2 size={15}/>{next[item.status]?.[1]}</>}</button>}</div></li>}
 return <section className="production-module" aria-label="Fluxo de produção">
  <div className="production-metrics"><article><span><Clock3 size={20}/></span><div><small>Em análise</small><strong>{analysis}</strong></div></article><article><span><Factory size={20}/></span><div><small>Em produção</small><strong>{inProgress}</strong></div></article><article><span><PackageCheck size={20}/></span><div><small>Prontos</small><strong>{ready}</strong></div></article></div>
  <section className="panel production-panel"><div className="orders-title"><div><h2>Ordens de produção</h2><p className="muted">Pedidos sem estoque começam pela análise do produto.</p></div><div className="production-heading-actions"><fieldset className="production-view-toggle" aria-label="Visualização da produção"><button type="button" className={view==='kanban'?'active':''} aria-pressed={view==='kanban'} onClick={()=>changeView('kanban')}><Columns3 size={16}/> Kanban</button><button type="button" className={view==='list'?'active':''} aria-pressed={view==='list'} onClick={()=>changeView('list')}><List size={16}/> Lista</button></fieldset><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'Atualizando…':'Atualizar'}</button></div></div>
   {message&&<output className="notice">{message}</output>}<div className="production-filters"><label><span>Pesquisar</span><span className="order-input-wrap"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Produto, cliente ou pedido"/></span></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value as 'todos'|ProductionStatus)}><option value="todos">Todos os status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{(query||status!=='todos')&&<button className="secondary" onClick={()=>{setQuery('');setStatus('todos')}}><FilterX size={16}/> Limpar filtros</button>}</div>
   {error&&<p className="global-alert" role="alert">{error}</p>}{loading?<div className="orders-empty">Carregando produção…</div>:view==='kanban'?<div className="production-board" aria-label="Kanban da produção">{statusOrder.filter(columnStatus=>status==='todos'||status===columnStatus).map(columnStatus=>{const columnItems=visible.filter(item=>item.status===columnStatus);return <section className={`production-column production-column-${columnStatus}`} key={columnStatus}><header><h3>{labels[columnStatus]}</h3><span>{columnItems.length}</span></header>{columnItems.length?<ul>{columnItems.map(item=>renderCard(item,true))}</ul>:<p className="production-column-empty">Nenhuma ordem nesta etapa.</p>}</section>})}</div>:visible.length===0?<div className="orders-empty"><Factory size={30}/><h3>Nenhuma ordem encontrada</h3><p>As necessidades de produção aparecerão após a aprovação dos pedidos.</p></div>:<ul className="production-list">{visible.map(item=>renderCard(item))}</ul>}
  </section>
 </section>;
}
