'use client';
/* oxlint-disable next/no-img-element */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Clock3,Columns3,ExternalLink,Factory,FilterX,ImageIcon,List,PackageCheck,Pencil,Plus,RefreshCw,Search,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Dialog,DialogClose,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import './production.css';
import './production-enhancements.css';

type ProductionStatus='analise_produto'|'aguardando_producao'|'em_impressao'|'acabamento'|'pronto'|'cancelado';
type ProductionView='kanban'|'list';
type ProductionOrder={id:string;pedido_id:string|null;produto_id:string|null;produto_nome:string;quantidade:number;status:ProductionStatus;detalhes:string|null;link_referencia:string|null;foto_urls:string[];criado_em:string;pedido:{numero:number;cliente_nome:string}|null};
type RawProduction=Omit<ProductionOrder,'pedido'>&{pedido:{numero:number;cliente_nome:string}|{numero:number;cliente_nome:string}[]|null};
type ProductionForm={produto_nome:string;quantidade:string;status:ProductionStatus;detalhes:string;link_referencia:string};

const environment=import.meta.env.BASE_URL.includes('/desenvolvimento/')?'desenvolvimento':'producao';
const labels:Record<ProductionStatus,string>={analise_produto:'Análise do produto',aguardando_producao:'Aguardando produção',em_impressao:'Em impressão',acabamento:'Acabamento',pronto:'Pronto',cancelado:'Cancelado'};
const statusOrder:ProductionStatus[]=['analise_produto','aguardando_producao','em_impressao','acabamento','pronto','cancelado'];
const next:Partial<Record<ProductionStatus,[ProductionStatus,string]>>={analise_produto:['aguardando_producao','Concluir análise'],aguardando_producao:['em_impressao','Iniciar impressão'],em_impressao:['acabamento','Enviar para acabamento'],acabamento:['pronto','Finalizar produção']};
const emptyForm:ProductionForm={produto_nome:'',quantidade:'1',status:'analise_produto',detalhes:'',link_referencia:''};
const orderNumber=(value:number)=>`#${String(value).padStart(4,'0')}`;

export default function Production({userId}:{userId:string}){
 const viewKey=`farm.productionView.${environment}`;
 const draftKey=`farm.productionDraft.${environment}.${userId}`;
 const [items,setItems]=useState<ProductionOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'todos'|ProductionStatus>('todos'),[updating,setUpdating]=useState<string|null>(null),[view,setView]=useState<ProductionView>('kanban');
 const [dialogOpen,setDialogOpen]=useState(false),[editing,setEditing]=useState<ProductionOrder|null>(null),[form,setForm]=useState<ProductionForm>(emptyForm),[photo,setPhoto]=useState<File|null>(null),[saving,setSaving]=useState(false),[draftRestored,setDraftRestored]=useState(false);

 const load=useCallback(async()=>{setLoading(true);setError('');const {data,error:loadError}=await supabase.from('farm_production_orders').select('id,pedido_id,produto_id,produto_nome,quantidade,status,detalhes,link_referencia,foto_urls,criado_em,pedido:farm_orders(numero,cliente_nome)').eq('ambiente',environment).order('criado_em',{ascending:false});if(loadError){setError('Não foi possível carregar as ordens de produção.');setItems([])}else setItems(((data||[]) as unknown as RawProduction[]).map(item=>({...item,quantidade:Number(item.quantidade),pedido:Array.isArray(item.pedido)?item.pedido[0]||null:item.pedido})));setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=sessionStorage.getItem(viewKey);if(saved==='kanban'||saved==='list')setView(saved);try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null') as {open?:boolean;form?:Partial<ProductionForm>}|null;if(draft?.open){setForm({...emptyForm,...draft.form});setDialogOpen(true);setMessage('Rascunho do novo card recuperado. Se havia uma foto, escolha o arquivo novamente.')}}catch{sessionStorage.removeItem(draftKey)}setDraftRestored(true)},0);return()=>window.clearTimeout(timer)},[draftKey,viewKey]);
 useEffect(()=>{if(!draftRestored||editing)return;if(dialogOpen)sessionStorage.setItem(draftKey,JSON.stringify({open:true,form}));else sessionStorage.removeItem(draftKey)},[dialogOpen,draftKey,draftRestored,editing,form]);

 const visible=useMemo(()=>{const term=query.trim().toLocaleLowerCase('pt-BR');return items.filter(item=>(status==='todos'||item.status===status)&&(!term||[item.produto_nome,item.pedido?.cliente_nome,item.pedido?.numero].join(' ').toLocaleLowerCase('pt-BR').includes(term)))},[items,query,status]);
 const analysis=items.filter(item=>item.status==='analise_produto').length,inProgress=items.filter(item=>['aguardando_producao','em_impressao','acabamento'].includes(item.status)).length,ready=items.filter(item=>item.status==='pronto').length;

 function changeView(nextView:ProductionView){setView(nextView);sessionStorage.setItem(viewKey,nextView)}
 function openCreate(){setEditing(null);setForm(emptyForm);setPhoto(null);setMessage('');setDialogOpen(true)}
 function openEdit(item:ProductionOrder){setEditing(item);setForm({produto_nome:item.produto_nome,quantidade:String(item.quantidade),status:item.status,detalhes:item.detalhes||'',link_referencia:item.link_referencia||''});setPhoto(null);setMessage('');setDialogOpen(true)}
 function closeDialog(){setDialogOpen(false);setEditing(null);setForm(emptyForm);setPhoto(null);sessionStorage.removeItem(draftKey)}

 async function syncParentOrder(orderId:string|null){if(!orderId)return;const {data:siblings}=await supabase.from('farm_production_orders').select('status').eq('pedido_id',orderId);if(!siblings?.length)return;const completed=siblings.every(row=>row.status==='pronto'||row.status==='cancelado');const {data:order}=await supabase.from('farm_orders').select('status').eq('id',orderId).maybeSingle();if(order&&['cancelado','reprovado','entregue'].includes(order.status))return;await supabase.from('farm_orders').update({status:completed?'pronto':'em_producao',atualizado_em:new Date().toISOString()}).eq('id',orderId)}

 async function saveCard(event:React.SyntheticEvent<HTMLFormElement>){event.preventDefault();const quantity=Math.floor(Number(form.quantidade));if(!form.produto_nome.trim()||!Number.isFinite(quantity)||quantity<1){setMessage('Informe o produto e uma quantidade válida.');return}setSaving(true);setMessage('');let uploadedPath:string|null=null;try{let foto_urls=editing?.foto_urls||[];if(photo){const extension=(photo.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();uploadedPath=`${userId}/production/${editing?.id||crypto.randomUUID()}/${crypto.randomUUID()}.${extension||'jpg'}`;const upload=await supabase.storage.from('orders').upload(uploadedPath,photo,{contentType:photo.type||undefined,upsert:false});if(upload.error)throw upload.error;foto_urls=[supabase.storage.from('orders').getPublicUrl(uploadedPath).data.publicUrl,...foto_urls]}const values={produto_nome:form.produto_nome.trim(),quantidade:quantity,status:form.status,detalhes:form.detalhes.trim()||null,link_referencia:form.link_referencia.trim()||null,foto_urls,atualizado_em:new Date().toISOString()};if(editing){const {error:updateError}=await supabase.from('farm_production_orders').update(values).eq('id',editing.id);if(updateError)throw updateError;await syncParentOrder(editing.pedido_id)}else{const {error:insertError}=await supabase.from('farm_production_orders').insert({...values,pedido_id:null,item_pedido_id:null,produto_id:null,ambiente:environment});if(insertError)throw insertError}closeDialog();setMessage(editing?'Card de produção atualizado.':'Novo card adicionado à produção.');await load()}catch{if(uploadedPath)await supabase.storage.from('orders').remove([uploadedPath]);setMessage('Não foi possível salvar o card. Confira os dados e tente novamente.')}finally{setSaving(false)}}

 async function advance(item:ProductionOrder){const action=next[item.status];if(!action)return;setUpdating(item.id);setMessage('');const [newStatus,label]=action;const {error:updateError}=await supabase.from('farm_production_orders').update({status:newStatus,atualizado_em:new Date().toISOString()}).eq('id',item.id);if(updateError)setMessage('Não foi possível atualizar a produção.');else{await syncParentOrder(item.pedido_id);setMessage(`${item.produto_nome}: ${label.toLocaleLowerCase('pt-BR')} registrado.`);await load()}setUpdating(null)}
 function renderCard(item:ProductionOrder,kanban=false){return <li key={item.id} className={`production-card${kanban?' production-kanban-card':''}`}><button type="button" className="production-card-hit" aria-label={`${item.produto_nome}. Clique duas vezes para alterar.`} onDoubleClick={()=>openEdit(item)}><span className="sr-only">Clique duas vezes para abrir e alterar {item.produto_nome}</span></button>{item.foto_urls?.[0]?<img src={item.foto_urls[0]} alt={`Referência de ${item.produto_nome}`}/>:<span className="production-placeholder"><ImageIcon size={25}/></span>}<div className="production-main"><small>{item.pedido?`${orderNumber(item.pedido.numero)} · ${item.pedido.cliente_nome}`:'Produção manual'}</small><strong>{item.produto_nome}</strong><span>{item.quantidade} {item.quantidade===1?'unidade':'unidades'}</span>{item.detalhes&&<p>{item.detalhes}</p>}</div><span className={`production-status production-${item.status}`}>{labels[item.status]}</span><div className="production-actions">{item.link_referencia&&<a className="secondary" href={item.link_referencia} target="_blank" rel="noreferrer">Abrir link <ExternalLink size={14}/></a>}<button className="secondary" onClick={()=>openEdit(item)}><Pencil size={14}/> Abrir e alterar</button>{next[item.status]&&<button disabled={updating===item.id} onClick={()=>void advance(item)}>{updating===item.id?'Atualizando…':<><CheckCircle2 size={15}/>{next[item.status]?.[1]}</>}</button>}</div></li>}

 return <section className="production-module" aria-label="Fluxo de produção">
  <div className="production-metrics"><article><span><Clock3 size={20}/></span><div><small>Em análise</small><strong>{analysis}</strong></div></article><article><span><Factory size={20}/></span><div><small>Em produção</small><strong>{inProgress}</strong></div></article><article><span><PackageCheck size={20}/></span><div><small>Prontos</small><strong>{ready}</strong></div></article></div>
  <section className="panel production-panel"><div className="orders-title"><div><h2>Ordens de produção</h2><p className="muted">Pedidos sem estoque começam pela análise do produto. Também é possível incluir um card manualmente.</p></div><div className="production-heading-actions"><button onClick={openCreate}><Plus size={16}/> Novo card</button><fieldset className="production-view-toggle" aria-label="Visualização da produção"><button type="button" className={view==='kanban'?'active':''} aria-pressed={view==='kanban'} onClick={()=>changeView('kanban')}><Columns3 size={16}/> Kanban</button><button type="button" className={view==='list'?'active':''} aria-pressed={view==='list'} onClick={()=>changeView('list')}><List size={16}/> Lista</button></fieldset><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/>{loading?'Atualizando…':'Atualizar'}</button></div></div>
   {message&&<output className="notice">{message}</output>}<div className="production-filters"><label><span>Pesquisar</span><span className="order-input-wrap"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Produto, cliente ou pedido"/></span></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value as 'todos'|ProductionStatus)}><option value="todos">Todos os status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{(query||status!=='todos')&&<button className="secondary" onClick={()=>{setQuery('');setStatus('todos')}}><FilterX size={16}/> Limpar filtros</button>}</div>
   {error&&<p className="global-alert" role="alert">{error}</p>}{loading?<div className="orders-empty">Carregando produção…</div>:view==='kanban'?<div className="production-board" aria-label="Kanban da produção">{statusOrder.filter(columnStatus=>status==='todos'||status===columnStatus).map(columnStatus=>{const columnItems=visible.filter(item=>item.status===columnStatus);return <section className={`production-column production-column-${columnStatus}`} key={columnStatus}><header><h3>{labels[columnStatus]}</h3><span>{columnItems.length}</span></header>{columnItems.length?<ul>{columnItems.map(item=>renderCard(item,true))}</ul>:<p className="production-column-empty">Nenhuma ordem nesta etapa.</p>}</section>})}</div>:visible.length===0?<div className="orders-empty"><Factory size={30}/><h3>Nenhuma ordem encontrada</h3><p>Adicione um novo card ou aprove um pedido que precisa de produção.</p></div>:<ul className="production-list">{visible.map(item=>renderCard(item))}</ul>}
  </section>
  <Dialog open={dialogOpen} onOpenChange={open=>{if(!open)closeDialog()}}><DialogContent className="production-dialog" showCloseButton={false}><DialogClose className="product-dialog-close" aria-label="Fechar"><X size={19}/></DialogClose><DialogHeader><DialogTitle>{editing?'Alterar card de produção':'Novo card de produção'}</DialogTitle><DialogDescription>{editing?.pedido?`Este card está vinculado ao pedido ${orderNumber(editing.pedido.numero)}.`:'Registre uma demanda manual na esteira de produção.'}</DialogDescription></DialogHeader><form className="production-form" onSubmit={saveCard}><div className="production-form-fields"><label>Produto<input value={form.produto_nome} onChange={event=>setForm({...form,produto_nome:event.target.value})} required maxLength={160} placeholder="Nome do produto"/></label><label>Quantidade<input type="number" inputMode="numeric" min="1" step="1" value={form.quantidade} onChange={event=>setForm({...form,quantidade:event.target.value})} required/></label><label>Etapa<select value={form.status} onChange={event=>setForm({...form,status:event.target.value as ProductionStatus})}>{statusOrder.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><label className="wide-field">Detalhes<textarea value={form.detalhes} onChange={event=>setForm({...form,detalhes:event.target.value})} rows={4} placeholder="Cor, acabamento, medidas ou observações"/></label><label className="wide-field">Link de referência<input type="url" inputMode="url" value={form.link_referencia} onChange={event=>setForm({...form,link_referencia:event.target.value})} placeholder="https://..."/></label><label className="wide-field">Foto<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={event=>setPhoto(event.target.files?.[0]||null)}/><small className="field-hint">{editing?.foto_urls?.length?'Escolha uma imagem somente se quiser adicionar uma nova foto ao card.':'Opcional. A imagem será exibida no card.'}</small></label></div>{message&&<output className="notice">{message}</output>}<div className="form-actions"><button disabled={saving}>{saving?'Salvando…':editing?'Salvar alterações':'Adicionar card'}</button><button type="button" className="secondary" onClick={closeDialog}>Cancelar</button></div></form></DialogContent></Dialog>
 </section>;
}
