'use client';
import {useEffect,useState} from 'react';
import {Eraser,Save} from 'lucide-react';
import {blank,example,calculate,number,validSheet,type Sheet} from '@/lib/pricing';
import {money} from '@/lib/demo';
import {supabase} from '@/lib/supabase';
const key='sonho-product-sheet-v1';
const groups=[{title:'Lote e impressão',hint:'Informe o total de todas as placas do lote. O tempo compartilhado entra uma única vez.',fields:[['batch','Peças produzidas no lote'],['hours','Impressão do lote (horas)'],['watts','Potência média (W)'],['kwh','Energia (R$/kWh)'],['machine','Máquina sem energia (R$/hora)']]},{title:'Trabalho e acabamento',hint:'Trabalho manual é separado da impressão. Embalagem e acabamento são por peça.',fields:[['minutes','Trabalho manual do lote (minutos)'],['labor','Mão de obra (R$/hora)'],['finish','Acabamento por unidade (R$)'],['pack','Embalagem por unidade (R$)'],['loss','Reserva de perdas de material (%)']]},{title:'Canal de venda',hint:'Taxas percentuais incidem sobre o preço final efetivamente cobrado. Valores fixos e frete são por unidade vendida. Use 0 onde não se aplica.',fields:[['commission','Comissão (%)'],['payment','Taxa de pagamento (%)'],['tax','Impostos (%)'],['fixed','Tarifa fixa por unidade (R$)'],['shipping','Frete pago por você por unidade (R$)'],['margin','Margem desejada sobre a venda (%)'],['price','Preço final que pretende cobrar (R$) — opcional']]}];
export default function ProductSheet({userId}:{userId:string}){const [sheet,setSheet]=useState<Sheet>(blank),[loaded,setLoaded]=useState(false),[status,setStatus]=useState(''),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);const {errors,result}=calculate(sheet);
 useEffect(()=>{let live=true;(async()=>{setStatus('Carregando ficha…');try{const {data,error}=await supabase.from('farm_product_sheets').select('sheet').eq('id',userId).maybeSingle();if(error)throw error;if(data&&validSheet(data.sheet)){if(live){setSheet(data.sheet);setSaved(false);setStatus('Ficha recuperada. Revise os dados e clique em Salvar produto.')}localStorage.removeItem(key)}else{const legacy=localStorage.getItem(key);if(legacy){const parsed=JSON.parse(legacy);if(validSheet(parsed)&&live){setSheet(parsed);setSaved(false);setStatus('Encontramos sua ficha anterior. Revise os dados e clique em Salvar produto.')}}else if(live)setStatus('Preencha uma nova ficha.')}}catch{if(live)setStatus('Não foi possível carregar sua ficha. Tente novamente.')}finally{if(live)setLoaded(true)}})();return()=>{live=false}},[userId]);
 const change=(k:keyof Sheet,v:string)=>{setSheet(p=>({...p,[k]:v}));setSaved(false);setStatus('Alterações ainda não salvas.')};
 async function saveProduct(){if(!result||saving)return;setSaving(true);setStatus('Salvando produto…');const {error:sheetError}=await supabase.from('farm_product_sheets').upsert({id:userId,sheet,updated_at:new Date().toISOString()},{onConflict:'id'});if(sheetError){setStatus('Não foi possível salvar a ficha. Nenhum produto foi criado.');setSaving(false);return}const id=`farm_${crypto.randomUUID()}`;const price=result.price??result.suggested;const materials=sheet.materials.map(material=>material.name.trim()).filter(Boolean).join(', ');const notes=`Criado pela calculadora. Custo por unidade: ${money(result.unit)}. Lote calculado: ${sheet.batch} peça(s).${materials?` Filamentos: ${materials}.`:''}`;const {error:productError}=await supabase.from('farm_portfolio_products').insert({airtable_record_id:id,nome:sheet.name.trim(),categoria:null,categoria_id:null,preco_venda:price,tempo_producao_h:number(sheet.hours),estoque:0,ativo:true,observacoes:notes,exibir_portfolio:false,foto_urls:[]});if(productError){setStatus('A ficha foi salva, mas o produto não pôde ser criado no Portfólio. Tente novamente.');setSaving(false);return}localStorage.removeItem(key);setSaved(true);setStatus('Produto salvo e criado no Portfólio como não publicado.');setSaving(false)}
 async function clearSheet(){if(saving)return;setSaving(true);const cleared=structuredClone(blank);setSheet(cleared);setSaved(false);localStorage.removeItem(key);const {error}=await supabase.from('farm_product_sheets').upsert({id:userId,sheet:cleared,updated_at:new Date().toISOString()},{onConflict:'id'});setStatus(error?'A tela foi limpa, mas a ficha anterior pode reaparecer ao entrar novamente. Nenhum produto foi criado.':'Calculadora limpa. Nenhum produto foi criado no Portfólio.');setSaving(false)}
 function field(k:string,label:string){return <label key={k} htmlFor={`field-${k}`}>{label}<input id={`field-${k}`} inputMode="decimal" value={sheet[k as keyof Sheet] as string} onChange={e=>change(k as keyof Sheet,e.target.value)} aria-invalid={!!errors[k]} aria-describedby={errors[k]?`error-${k}`:undefined}/>{errors[k]&&<span className="field-error" id={`error-${k}`}>{errors[k]}</span>}</label>}
 return <div className="product-sheet"><section className="panel"><div className="section-title"><div><h2>Ficha do seu produto</h2><p className="muted">Preencha os dados para calcular o custo e o preço sugerido.</p></div><span className="badge">{saved?'Produto criado':'Rascunho'}</span></div><p className="callout">Ao salvar, a ficha fica protegida na sua conta e o produto é criado no Portfólio como não publicado. Depois você poderá adicionar categoria, foto, tamanho e link do arquivo.</p><div className="actions"><button disabled={!loaded||!result||saving||saved} onClick={()=>void saveProduct()}><Save size={17}/>{saving?'Salvando…':saved?'Produto salvo':'Salvar produto'}</button><button className="secondary" disabled={!loaded||saving} onClick={()=>void clearSheet()}><Eraser size={17}/> Limpar</button><button className="secondary" disabled={saving} onClick={()=>{setSheet(structuredClone(example));setSaved(false);setStatus('Exemplo carregado para edição.')}}>Carregar exemplo fictício</button></div><p role="status" className="notice">{status}</p><label htmlFor="product-name">Nome do produto<input id="product-name" value={sheet.name} onChange={e=>change('name',e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name?"name-error":undefined}/>{errors.name&&<span className="field-error" id="name-error">{errors.name}</span>}</label></section>
 <div className="calculator-layout"><section className="panel calculator-result" aria-live="polite"><p className="eyebrow">RESULTADO DA FICHA</p><h2>{sheet.name||'Seu produto'}</h2>{!result?<><p className="callout">Cálculo incompleto. Revise os campos indicados abaixo. Campo vazio não significa custo zero.</p><p>{Object.keys(errors).length} {Object.keys(errors).length===1?'campo precisa':'campos precisam'} de revisão.</p></>:<><div className="result-pair"><div><small>Custo por unidade</small><strong>{money(result.unit)}</strong></div><div><small>Preço mínimo para a margem desejada</small><strong>{money(result.suggested)}</strong></div></div><dl>{result.parts.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{money(value)}</dd></div>)}<div><dt>Custo do lote</dt><dd>{money(result.batch)}</dd></div><div><dt>Tarifa fixa + frete por unidade</dt><dd>{money(result.expenses)}</dd></div>{result.price!==null&&<><div><dt>Preço informado</dt><dd>{money(result.price)}</dd></div><div><dt>Taxas no preço informado</dt><dd>{money(result.price*result.rates)}</dd></div><div><dt>Contribuição por unidade</dt><dd>{money(result.contribution!)}</dd></div><div><dt>Margem no preço informado</dt><dd>{result.actualMargin!.toLocaleString('pt-BR',{maximumFractionDigits:2})}%</dd></div></>}</dl>{result.contribution!==null&&result.contribution<0&&<p className="field-error">O preço informado não cobre os custos e as despesas desta ficha.</p>}<p className="footnote">Margem é a parcela da venda que sobra após os custos e taxas informados; não é lucro líquido do negócio. A sugestão é arredondada para cima no centavo. Nenhum preço é aprovado automaticamente.</p></>}</section>
 <div className="calculator-fields"><section className="panel"><h2>Materiais do lote</h2><p className="muted">Consumo em gramas, incluindo suportes e purga. Preço de compra por kg. Não some a mesma perda novamente na reserva percentual.</p>{sheet.materials.map((m,i)=><fieldset key={i} className="material-card"><legend>Filamento {i+1}</legend>{([['name','Material, marca e cor'],['grams','Consumo do lote (g)'],['kgPrice','Preço de compra (R$/kg)']] as const).map(([k,label])=><label key={k}>{label}<input inputMode={k==='name'?'text':'decimal'} value={m[k]} onChange={e=>{setSheet(p=>({...p,materials:p.materials.map((old,j)=>j===i?{...old,[k]:e.target.value}:old)}));setSaved(false);setStatus('Alterações ainda não salvas.')}} aria-invalid={!!errors[`m${i}${k}`]} aria-describedby={errors[`m${i}${k}`]?`material-error-${i}-${k}`:undefined}/>{errors[`m${i}${k}`]&&<span className="field-error" id={`material-error-${i}-${k}`}>{errors[`m${i}${k}`]}</span>}</label>)}<button className="secondary" disabled={sheet.materials.length===1} onClick={()=>{setSheet(p=>({...p,materials:p.materials.filter((_,j)=>j!==i)}));setSaved(false);setStatus('Material removido do rascunho.')}}>Remover filamento {i+1}</button></fieldset>)}<button className="secondary" disabled={sheet.materials.length>=50} onClick={()=>{setSheet(p=>({...p,materials:[...p.materials,{name:'',grams:'',kgPrice:''}]}));setSaved(false);setStatus('Novo filamento adicionado. Preencha os campos.')}}>Adicionar filamento</button></section>{groups.map(group=><section className="panel" key={group.title}><h2>{group.title}</h2><p className="muted">{group.hint}</p><div className="fields">{group.fields.map(([k,label])=>field(k,label))}</div>{group.title==='Trabalho e acabamento'&&<p className="footnote">Reserva de perdas aplicada somente ao custo teórico dos materiais. Não é um registro de falhas reais. Preço sugerido = (custo unitário + tarifa fixa + frete) ÷ (1 − taxas percentuais − margem desejada).</p>}</section>)}</div></div></div>
}


