'use client';
import {useEffect,useState} from 'react';
import {blank,example,calculate,validSheet,type Sheet} from '@/lib/pricing';
import {money} from '@/lib/demo';
const key='sonho-product-sheet-v1';
const groups=[{title:'Lote e impressão',hint:'Informe o total de todas as placas do lote. O tempo compartilhado entra uma única vez.',fields:[['batch','Peças produzidas no lote'],['hours','Impressão do lote (horas)'],['watts','Potência média (W)'],['kwh','Energia (R$/kWh)'],['machine','Máquina sem energia (R$/hora)']]},{title:'Trabalho e acabamento',hint:'Trabalho manual é separado da impressão. Embalagem e acabamento são por peça.',fields:[['minutes','Trabalho manual do lote (minutos)'],['labor','Mão de obra (R$/hora)'],['finish','Acabamento por unidade (R$)'],['pack','Embalagem por unidade (R$)'],['loss','Reserva de perdas de material (%)']]},{title:'Canal de venda',hint:'Taxas percentuais incidem sobre o preço final efetivamente cobrado. Valores fixos e frete são por unidade vendida. Use 0 onde não se aplica.',fields:[['commission','Comissão (%)'],['payment','Taxa de pagamento (%)'],['tax','Impostos (%)'],['fixed','Tarifa fixa por unidade (R$)'],['shipping','Frete pago por você por unidade (R$)'],['margin','Margem desejada sobre a venda (%)'],['price','Preço final que pretende cobrar (R$) — opcional']]}];
export default function ProductSheet(){const [sheet,setSheet]=useState<Sheet>(blank),[loaded,setLoaded]=useState(false),[status,setStatus]=useState(''),[saved,setSaved]=useState(false);const {errors,result}=calculate(sheet);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const data=JSON.parse(raw);if(validSheet(data)){setSheet(data);setSaved(true);setStatus('Ficha recuperada deste navegador.')}else setStatus('A ficha salva não pôde ser lida. Preencha uma nova ficha.')}}catch{setStatus('Não foi possível acessar o armazenamento deste navegador.')}setLoaded(true)},[]);
 const change=(k:keyof Sheet,v:string)=>{setSheet(p=>({...p,[k]:v}));setSaved(false);setStatus('Alterações ainda não salvas.')};
 function field(k:string,label:string){return <label key={k} htmlFor={`field-${k}`}>{label}<input id={`field-${k}`} inputMode="decimal" value={sheet[k as keyof Sheet] as string} onChange={e=>change(k as keyof Sheet,e.target.value)} aria-invalid={!!errors[k]} aria-describedby={errors[k]?`error-${k}`:undefined}/>{errors[k]&&<span className="field-error" id={`error-${k}`}>{errors[k]}</span>}</label>}
 return <div className="product-sheet"><section className="panel"><div className="section-title"><div><h2>Ficha do seu produto</h2><p className="muted">Preencha os dados para calcular o custo e o preço sugerido.</p></div><span className="badge">{saved?'Salva neste navegador':'Rascunho'}</span></div><p className="callout">Esta ficha é independente dos pedidos de demonstração. Você pode salvar uma ficha neste navegador; ela não é sincronizada com outros aparelhos. Salvar substitui a ficha anterior.</p><div className="actions"><button disabled={!loaded} onClick={()=>{try{localStorage.setItem(key,JSON.stringify(sheet));setSaved(true);setStatus('Ficha salva neste navegador. Pode recarregar a página.')}catch{setStatus('Não foi possível salvar. O navegador pode estar sem espaço ou com armazenamento bloqueado.')}}}>Salvar neste navegador</button><button className="secondary" onClick={()=>{setSheet(structuredClone(example));setSaved(false);setStatus('Exemplo carregado para edição. A ficha salva só muda quando você salvar.')}}>Carregar exemplo fictício</button></div><p role="status" className="notice">{status}</p><label htmlFor="product-name">Nome do produto<input id="product-name" value={sheet.name} onChange={e=>change('name',e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name?"name-error":undefined}/>{errors.name&&<span className="field-error" id="name-error">{errors.name}</span>}</label></section>
 <div className="calculator-layout"><section className="panel calculator-result" aria-live="polite"><p className="eyebrow">RESULTADO DA FICHA</p><h2>{sheet.name||'Seu produto'}</h2>{!result?<><p className="callout">Cálculo incompleto. Revise os campos indicados abaixo. Campo vazio não significa custo zero.</p><p>{Object.keys(errors).length} {Object.keys(errors).length===1?'campo precisa':'campos precisam'} de revisão.</p></>:<><div className="result-pair"><div><small>Custo por unidade</small><strong>{money(result.unit)}</strong></div><div><small>Preço mínimo para a margem desejada</small><strong>{money(result.suggested)}</strong></div></div><dl>{result.parts.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{money(value)}</dd></div>)}<div><dt>Custo do lote</dt><dd>{money(result.batch)}</dd></div><div><dt>Tarifa fixa + frete por unidade</dt><dd>{money(result.expenses)}</dd></div>{result.price!==null&&<><div><dt>Preço informado</dt><dd>{money(result.price)}</dd></div><div><dt>Taxas no preço informado</dt><dd>{money(result.price*result.rates)}</dd></div><div><dt>Contribuição por unidade</dt><dd>{money(result.contribution!)}</dd></div><div><dt>Margem no preço informado</dt><dd>{result.actualMargin!.toLocaleString('pt-BR',{maximumFractionDigits:2})}%</dd></div></>}</dl>{result.contribution!==null&&result.contribution<0&&<p className="field-error">O preço informado não cobre os custos e as despesas desta ficha.</p>}<p className="footnote">Margem é a parcela da venda que sobra após os custos e taxas informados; não é lucro líquido do negócio. A sugestão é arredondada para cima no centavo. Nenhum preço é aprovado automaticamente.</p></>}</section>
 <div className="calculator-fields"><section className="panel"><h2>Materiais do lote</h2><p className="muted">Consumo em gramas, incluindo suportes e purga. Preço de compra por kg. Não some a mesma perda novamente na reserva percentual.</p>{sheet.materials.map((m,i)=><fieldset key={i} className="material-card"><legend>Filamento {i+1}</legend>{([['name','Material, marca e cor'],['grams','Consumo do lote (g)'],['kgPrice','Preço de compra (R$/kg)']] as const).map(([k,label])=><label key={k}>{label}<input inputMode={k==='name'?'text':'decimal'} value={m[k]} onChange={e=>{setSheet(p=>({...p,materials:p.materials.map((old,j)=>j===i?{...old,[k]:e.target.value}:old)}));setSaved(false);setStatus('Alterações ainda não salvas.')}} aria-invalid={!!errors[`m${i}${k}`]} aria-describedby={errors[`m${i}${k}`]?`material-error-${i}-${k}`:undefined}/>{errors[`m${i}${k}`]&&<span className="field-error" id={`material-error-${i}-${k}`}>{errors[`m${i}${k}`]}</span>}</label>)}<button className="secondary" disabled={sheet.materials.length===1} onClick={()=>{setSheet(p=>({...p,materials:p.materials.filter((_,j)=>j!==i)}));setSaved(false);setStatus('Material removido do rascunho.')}}>Remover filamento {i+1}</button></fieldset>)}<button className="secondary" disabled={sheet.materials.length>=50} onClick={()=>{setSheet(p=>({...p,materials:[...p.materials,{name:'',grams:'',kgPrice:''}]}));setSaved(false);setStatus('Novo filamento adicionado. Preencha os campos.')}}>Adicionar filamento</button></section>{groups.map(group=><section className="panel" key={group.title}><h2>{group.title}</h2><p className="muted">{group.hint}</p><div className="fields">{group.fields.map(([k,label])=>field(k,label))}</div>{group.title==='Trabalho e acabamento'&&<p className="footnote">Reserva de perdas aplicada somente ao custo teórico dos materiais. Não é um registro de falhas reais. Preço sugerido = (custo unitário + tarifa fixa + frete) ÷ (1 − taxas percentuais − margem desejada).</p>}</section>)}</div></div></div>
}


