'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {CalendarDays,CircleDollarSign,Download,History,RefreshCw,RotateCcw,Search,WalletCards,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import './receivables.css';

type Payment={id:string;tipo:'recebimento'|'estorno';valor:number;data_movimentacao:string;forma_pagamento:string;observacao:string|null;motivo:string|null;pagamento_origem_id:string|null;criado_em:string};
type Order={numero:number;cliente_nome:string;vendedor_nome:string;data_pedido:string;status:string;forma_pagamento:string|null};
type RawFinancial={id:string;pedido_id:string;valor_total:number|string;data_prevista_pagamento:string|null;observacao:string|null;status:string;criado_em:string;atualizado_em:string;pedido:Order|Order[]|null;pagamentos:Payment[]};
type Financial=Omit<RawFinancial,'valor_total'|'pedido'|'pagamentos'>&{valor_total:number;pedido:Order|null;pagamentos:Payment[];received:number;balance:number;displayStatus:string};

const environment=import.meta.env.BASE_URL.includes('/desenvolvimento/')?'desenvolvimento':'producao';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const statusLabels:Record<string,string>={pendente:'Pendente',parcial:'Parcial',pago:'Pago',vencido:'Vencido',cancelado:'Cancelado',aguardando_devolucao:'Aguardando devolução'};
const methods=['Pix','Dinheiro','Cartão de débito','Cartão de crédito','Transferência','Outro'];
const padOrder=(value:number)=>`#${String(value).padStart(4,'0')}`;
const localDate=(value:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'Não informada';

function normalize(row:RawFinancial):Financial{
 const payments=(row.pagamentos||[]).map(item=>({...item,valor:Number(item.valor)})).sort((a,b)=>`${b.data_movimentacao}${b.criado_em}`.localeCompare(`${a.data_movimentacao}${a.criado_em}`));
 const received=payments.reduce((sum,item)=>sum+(item.tipo==='recebimento'?item.valor:-item.valor),0),total=Number(row.valor_total);
 const overdue=['pendente','parcial'].includes(row.status)&&Boolean(row.data_prevista_pagamento)&&row.data_prevista_pagamento!<new Date().toISOString().slice(0,10);
 return {...row,valor_total:total,pedido:Array.isArray(row.pedido)?row.pedido[0]||null:row.pedido,pagamentos:payments,received:Math.max(0,received),balance:Math.max(0,total-received),displayStatus:overdue?'vencido':row.status};
}

export default function Receivables({administrator}:{administrator:boolean}){
 const [items,setItems]=useState<Financial[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('todos'),[period,setPeriod]=useState('todos'),[selectedId,setSelectedId]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const [dueDate,setDueDate]=useState(''),[note,setNote]=useState(''),[paymentValue,setPaymentValue]=useState(''),[paymentDate,setPaymentDate]=useState(new Date().toISOString().slice(0,10)),[paymentMethod,setPaymentMethod]=useState('Pix'),[paymentNote,setPaymentNote]=useState('');
 const load=useCallback(async()=>{setLoading(true);setMessage('');const {data,error}=await supabase.from('farm_order_financials').select('id,pedido_id,valor_total,data_prevista_pagamento,observacao,status,criado_em,atualizado_em,pedido:farm_orders(numero,cliente_nome,vendedor_nome,data_pedido,status,forma_pagamento),pagamentos:farm_order_payments(id,tipo,valor,data_movimentacao,forma_pagamento,observacao,motivo,pagamento_origem_id,criado_em)').eq('ambiente',environment).order('atualizado_em',{ascending:false});if(error){setItems([]);setMessage('Não foi possível carregar os recebimentos.')}else setItems(((data||[]) as unknown as RawFinancial[]).map(normalize));setLoading(false)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const selected=items.find(item=>item.id===selectedId)||null;
 function openDetails(item:Financial){setDueDate(item.data_prevista_pagamento||'');setNote(item.observacao||'');setPaymentValue(item.balance?item.balance.toFixed(2):'');setSelectedId(item.id)}
 const filtered=useMemo(()=>items.filter(item=>{const text=`${item.pedido?.numero||''} ${item.pedido?.cliente_nome||''} ${item.pedido?.vendedor_nome||''}`.toLocaleLowerCase('pt-BR');if(query&& !text.includes(query.toLocaleLowerCase('pt-BR')))return false;if(status!=='todos'&&item.displayStatus!==status)return false;if(period!=='todos'){const limit=new Date();limit.setDate(limit.getDate()-Number(period));if(!item.pedido?.data_pedido||new Date(`${item.pedido.data_pedido}T12:00:00`)<limit)return false}return true}),[items,query,status,period]);
 const totals=useMemo(()=>filtered.reduce((acc,item)=>({total:acc.total+item.valor_total,received:acc.received+item.received,balance:acc.balance+item.balance}),{total:0,received:0,balance:0}),[filtered]);
 const reversedIds=useMemo(()=>new Set(selected?.pagamentos.filter(p=>p.tipo==='estorno').map(p=>p.pagamento_origem_id)||[]),[selected]);
 async function saveDetails(){if(!selected)return;setSaving(true);const {error}=await supabase.rpc('farm_update_order_financial',{p_order_id:selected.pedido_id,p_due_date:dueDate||null,p_note:note.trim()||null});setMessage(error?error.message:'Informações de cobrança atualizadas.');if(!error)await load();setSaving(false)}
 async function registerPayment(){if(!selected)return;const value=Number(paymentValue.replace(',','.'));if(!Number.isFinite(value)||value<=0){setMessage('Informe um valor recebido maior que zero.');return}setSaving(true);const {error}=await supabase.rpc('farm_register_order_payment',{p_order_id:selected.pedido_id,p_value:value,p_payment_date:paymentDate,p_method:paymentMethod,p_note:paymentNote.trim()||null});setMessage(error?error.message:'Pagamento registrado.');if(!error){setPaymentNote('');await load()}setSaving(false)}
 async function reversePayment(payment:Payment){const reason=window.prompt('Informe o motivo do estorno:')?.trim();if(!reason)return;setSaving(true);const {error}=await supabase.rpc('farm_reverse_order_payment',{p_payment_id:payment.id,p_reason:reason});setMessage(error?error.message:'Pagamento estornado.');if(!error)await load();setSaving(false)}
 async function exportPdf(){if(!filtered.length){setMessage('Não há recebimentos nos filtros atuais.');return}const {jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'mm',format:'a4'}),width=doc.internal.pageSize.getWidth();let y=20;const page=()=>{doc.setFont('helvetica','bold');doc.setFontSize(15);doc.setTextColor(18,59,60);doc.text('Sonho em Camadas 3D · Recebimentos',14,14);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(90,105,112);doc.text(`Gerado em ${new Date().toLocaleString('pt-BR')} · ${filtered.length} pedido(s)`,width-14,14,{align:'right'});y=24};page();for(const item of filtered){if(y>275){doc.addPage();page()}doc.setFillColor(245,248,249);doc.roundedRect(14,y,width-28,22,2,2,'F');doc.setTextColor(23,52,65);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(`${padOrder(item.pedido?.numero||0)} · ${item.pedido?.cliente_nome||'Cliente'}`,18,y+7);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`${statusLabels[item.displayStatus]} · Previsto: ${localDate(item.data_prevista_pagamento)}`,18,y+14);doc.text(`Total ${money.format(item.valor_total)}   Recebido ${money.format(item.received)}   Saldo ${money.format(item.balance)}`,width-18,y+11,{align:'right'});y+=27}if(y>260){doc.addPage();page()}doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(`Total vendido: ${money.format(totals.total)}   Recebido: ${money.format(totals.received)}   Em aberto: ${money.format(totals.balance)}`,14,y+5);doc.save(`recebimentos-${new Date().toISOString().slice(0,10)}.pdf`);setMessage('Relatório gerado com os filtros aplicados.')}
 return <section className="receivables-module" aria-label="Controle de recebimentos">
  <div className="receivable-metrics"><article><CircleDollarSign/><div><small>Total dos pedidos</small><strong>{money.format(totals.total)}</strong></div></article><article><WalletCards/><div><small>Valor recebido</small><strong>{money.format(totals.received)}</strong></div></article><article><CalendarDays/><div><small>Saldo em aberto</small><strong>{money.format(totals.balance)}</strong></div></article></div>
  <section className="panel receivables-panel"><div className="receivables-title"><div><h2>Recebimentos por pedido</h2><p className="muted">Registre pagamentos integrais ou parciais e acompanhe o saldo.</p></div><div className="actions"><button className="secondary" onClick={()=>void exportPdf()}><Download size={16}/> Exportar PDF</button><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/> Atualizar</button></div></div>{message&&<output className="notice">{message}</output>}
   <div className="receivable-filters"><label>Pesquisar<span><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pedido, cliente ou vendedor"/></span></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="todos">Todo período</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></label></div>
   {loading?<div className="receivables-empty">Carregando…</div>:filtered.length===0?<div className="receivables-empty"><WalletCards size={31}/><h3>Nenhum recebimento encontrado</h3><p>O controle aparece quando um pedido é aprovado.</p></div>:<div className="receivable-list">{filtered.map(item=><button type="button" key={item.id} className="receivable-row" onClick={()=>openDetails(item)}><div><strong>{padOrder(item.pedido?.numero||0)}</strong><span>{item.pedido?.cliente_nome}</span><small>{item.pedido?.vendedor_nome||'Sem vendedor'} · {localDate(item.pedido?.data_pedido||null)}</small></div><div><small>Total</small><strong>{money.format(item.valor_total)}</strong></div><div><small>Recebido</small><strong>{money.format(item.received)}</strong></div><div><small>Saldo</small><strong>{money.format(item.balance)}</strong></div><div><small>Previsão</small><strong>{localDate(item.data_prevista_pagamento)}</strong></div><span className={`receivable-status status-${item.displayStatus}`}>{statusLabels[item.displayStatus]}</span></button>)}</div>}
  </section>
  {selected&&<div className="receivable-dialog-backdrop"><dialog open className="receivable-dialog" aria-label={`Recebimento do pedido ${padOrder(selected.pedido?.numero||0)}`}><header><div><small>PEDIDO</small><h2>{padOrder(selected.pedido?.numero||0)} · {selected.pedido?.cliente_nome}</h2></div><button className="secondary icon-button" aria-label="Fechar" onClick={()=>setSelectedId(null)}><X/></button></header><div className="receivable-dialog-summary"><div><small>Total</small><strong>{money.format(selected.valor_total)}</strong></div><div><small>Recebido</small><strong>{money.format(selected.received)}</strong></div><div><small>Saldo</small><strong>{money.format(selected.balance)}</strong></div></div>
   {administrator&&<><section className="receivable-form"><h3>Informações de cobrança</h3><div className="receivable-form-grid"><label>Data prevista<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label className="wide">Observação<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Condição combinada com o cliente"/></label></div><button className="secondary" disabled={saving} onClick={()=>void saveDetails()}>Salvar informações</button></section>{!['cancelado','aguardando_devolucao'].includes(selected.status)&&selected.balance>0&&<section className="receivable-form"><h3>Registrar pagamento</h3><div className="receivable-form-grid"><label>Valor recebido (R$)<input type="number" min="0.01" max={selected.balance} step="0.01" value={paymentValue} onChange={e=>setPaymentValue(e.target.value)}/></label><label>Data<input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><label>Forma<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{methods.map(method=><option key={method}>{method}</option>)}</select></label><label className="wide">Observação<input value={paymentNote} onChange={e=>setPaymentNote(e.target.value)} placeholder="Opcional"/></label></div><button disabled={saving} onClick={()=>void registerPayment()}>Registrar pagamento</button></section>}</>}
   <section className="payment-history"><h3><History size={18}/> Histórico</h3>{selected.pagamentos.length===0?<p className="muted">Nenhum pagamento registrado.</p>:<ul>{selected.pagamentos.map(payment=><li key={payment.id} className={payment.tipo==='estorno'?'reversal':''}><span>{payment.tipo==='recebimento'?'Pagamento':'Estorno'}<small>{localDate(payment.data_movimentacao)} · {payment.forma_pagamento}{payment.observacao?` · ${payment.observacao}`:''}{payment.motivo?` · Motivo: ${payment.motivo}`:''}</small></span><strong>{payment.tipo==='estorno'?'- ':''}{money.format(payment.valor)}</strong>{administrator&&payment.tipo==='recebimento'&&!reversedIds.has(payment.id)&&<button className="secondary" disabled={saving} onClick={()=>void reversePayment(payment)}><RotateCcw size={14}/> Estornar</button>}</li>)}</ul>}</section>
  </dialog></div>}
 </section>;
}
