'use client';
/* oxlint-disable next/no-img-element, react/react-compiler */
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Check,Download,PackagePlus,Pencil,RefreshCw,ShoppingBag,Trash2,Undo2,WalletCards,X} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import './sellers.css';

type Seller={id:string;nome:string;usuario_id:string|null;percentual_comissao:number;forma_pagamento_comissao:string|null};
type Product={airtable_record_id:string;nome:string;categoria:string|null;preco_venda:number|null;estoque:number|null;estoque_disponivel:number;foto_urls:string[];desconto_maximo_percentual:number};
type InventoryRow={product_id:string;estoque_disponivel:number};
type Remittance={id:string;numero:number;vendedor_id:string;status:string;data_envio:string;data_prevista_retorno:string|null;observacoes:string|null;confirmado_recebimento_em:string|null};
type Item={id:string;remessa_id:string;produto_id:string;produto_nome:string;categoria:string|null;foto_url:string|null;quantidade_enviada:number;preco_unitario:number;desconto_maximo_percentual:number;percentual_comissao:number};
type Sale={id:string;remessa_item_id:string;vendedor_id:string;grupo_venda_id:string|null;data_venda:string;quantidade:number;valor_total:number;valor_comissao:number;forma_pagamento:string|null;comprovante_paths:string[];status:string;cliente_nome:string|null};
type Occurrence={id:string;remessa_item_id:string;vendedor_id:string;tipo:string;quantidade:number;data_ocorrencia:string;tratamento:string|null;valor_responsabilidade:number;status:string};
type Closing={id:string;vendedor_id:string;competencia:string;status:string;total_vendas:number;total_comissao:number;total_responsabilidades:number;valor_liquido:number;pago_em:string|null};
type SellerOrder={id:string;numero:number;vendedor_id:string|null;vendedor_cadastro_id:string|null;cliente_nome:string;status:string;valor_total:number;criado_em:string};
type DraftItem={productId:string;quantity:string};
type SaleDraftItem={itemId:string;quantity:string;unitValue:string};
const environment='desenvolvimento';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const date=(value:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const statusLabel:Record<string,string>={rascunho:'Rascunho',enviada:'Aguardando recebimento',recebida:'Recebida',parcialmente_devolvida:'Devolução parcial',encerrada:'Encerrada',cancelada:'Cancelada',informada:'Pendente do fechamento',aprovada:'Aprovada',pago:'Pago'};

export default function Sellers({administrator,userId}:{administrator:boolean;userId:string}){
 const [tab,setTab]=useState<'overview'|'remittances'|'sales'|'closings'>('overview');
 const [sellers,setSellers]=useState<Seller[]>([]),[products,setProducts]=useState<Product[]>([]),[remittances,setRemittances]=useState<Remittance[]>([]),[items,setItems]=useState<Item[]>([]),[sales,setSales]=useState<Sale[]>([]),[occurrences,setOccurrences]=useState<Occurrence[]>([]),[closings,setClosings]=useState<Closing[]>([]),[orders,setOrders]=useState<SellerOrder[]>([]);
 const [selectedSeller,setSelectedSeller]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[remittanceMessage,setRemittanceMessage]=useState('');
 const [creating,setCreating]=useState(false),[workingRemittance,setWorkingRemittance]=useState(''),[editingRemittance,setEditingRemittance]=useState<Remittance|null>(null),[shippingDate,setShippingDate]=useState(new Date().toISOString().slice(0,10)),[returnDate,setReturnDate]=useState(''),[notes,setNotes]=useState(''),[draftItems,setDraftItems]=useState<DraftItem[]>([]),[pickerOpen,setPickerOpen]=useState(false),[pickerQuery,setPickerQuery]=useState(''),[pickerCategory,setPickerCategory]=useState('todos');
 const [registering,setRegistering]=useState(false),[saleItems,setSaleItems]=useState<SaleDraftItem[]>([]),[paymentMethod,setPaymentMethod]=useState('Pix'),[receiptFiles,setReceiptFiles]=useState<File[]>([]),[receiptInputKey,setReceiptInputKey]=useState(0),[actionItem,setActionItem]=useState(''),[actionType,setActionType]=useState<'sale'|'devolucao'|'perda'|'avaria'>('sale'),[actionQty,setActionQty]=useState('1'),[actionDate,setActionDate]=useState(new Date().toISOString().slice(0,10)),[customer,setCustomer]=useState(''),[treatment,setTreatment]=useState('absorvido_farm'),[responsibility,setResponsibility]=useState('0'),[actionNotes,setActionNotes]=useState('');
 const [competence,setCompetence]=useState(new Date().toISOString().slice(0,7));
 const [policyProduct,setPolicyProduct]=useState(''),[policyDiscount,setPolicyDiscount]=useState('0');

 const load=useCallback(async(clearMessage=false)=>{
  setLoading(true);if(clearMessage)setMessage('');
  const [sellerResult,productResult,inventoryResult,remittanceResult,itemResult,saleResult,occurrenceResult,closingResult,orderResult]=await Promise.all([
   supabase.from('farm_sellers').select('id,nome,usuario_id,percentual_comissao,forma_pagamento_comissao').eq('ambiente',environment).eq('ativo',true).order('nome'),
   supabase.from('farm_portfolio_products').select('airtable_record_id,nome,categoria,preco_venda,estoque,foto_urls,desconto_maximo_percentual').eq('ativo',true).order('nome'),
   supabase.rpc('farm_inventory_snapshot',{p_environment:environment}),
   supabase.from('farm_consignments').select('id,numero,vendedor_id,status,data_envio,data_prevista_retorno,observacoes,confirmado_recebimento_em').eq('ambiente',environment).order('numero',{ascending:false}),
   supabase.from('farm_consignment_items').select('*'),supabase.from('farm_consignment_sales').select('id,remessa_item_id,vendedor_id,grupo_venda_id,data_venda,quantidade,valor_total,valor_comissao,forma_pagamento,comprovante_paths,status,cliente_nome').eq('ambiente',environment).order('data_venda',{ascending:false}),
   supabase.from('farm_consignment_occurrences').select('id,remessa_item_id,vendedor_id,tipo,quantidade,data_ocorrencia,tratamento,valor_responsabilidade,status').eq('ambiente',environment).order('data_ocorrencia',{ascending:false}),
   supabase.from('farm_seller_closings').select('id,vendedor_id,competencia,status,total_vendas,total_comissao,total_responsabilidades,valor_liquido,pago_em').eq('ambiente',environment).order('competencia',{ascending:false}),
   supabase.from('farm_orders').select('id,numero,vendedor_id,vendedor_cadastro_id,cliente_nome,status,valor_total,criado_em').eq('ambiente',environment).order('numero',{ascending:false}),
  ]);
  const failure=[sellerResult,productResult,inventoryResult,remittanceResult,itemResult,saleResult,occurrenceResult,closingResult,orderResult].find(result=>result.error);
  if(failure?.error)setMessage(`Não foi possível carregar os dados (${failure.error.message}).`);
  const sellerData=(sellerResult.data||[]) as Seller[],inventoryData=(inventoryResult.data||[]) as InventoryRow[];
  setSellers(sellerData);setProducts(((productResult.data||[]) as Omit<Product,'estoque_disponivel'>[]).map(product=>({...product,estoque_disponivel:Number(inventoryData.find(item=>item.product_id===product.airtable_record_id)?.estoque_disponivel||0)})));setRemittances((remittanceResult.data||[]) as Remittance[]);setItems((itemResult.data||[]) as Item[]);setSales((saleResult.data||[]) as Sale[]);setOccurrences((occurrenceResult.data||[]) as Occurrence[]);setClosings((closingResult.data||[]) as Closing[]);setOrders((orderResult.data||[]) as SellerOrder[]);
  setSelectedSeller(current=>current||sellerData.find(seller=>seller.usuario_id===userId)?.id||sellerData[0]?.id||'');setLoading(false);
 },[userId]);
 useEffect(()=>{void load(true)},[load]);
 useEffect(()=>{setSaleItems([]);setReceiptFiles([]);setReceiptInputKey(current=>current+1);setActionItem('');setCustomer('');setActionNotes('')},[selectedSeller]);

 const visibleRemittances=useMemo(()=>remittances.filter(item=>!selectedSeller||item.vendedor_id===selectedSeller),[remittances,selectedSeller]);
 const visibleItems=useMemo(()=>items.filter(item=>visibleRemittances.some(remittance=>remittance.id===item.remessa_id)),[items,visibleRemittances]);
 const sellerSales=useMemo(()=>sales.filter(item=>!selectedSeller||item.vendedor_id===selectedSeller),[sales,selectedSeller]);
 const sellerOccurrences=useMemo(()=>occurrences.filter(item=>!selectedSeller||item.vendedor_id===selectedSeller),[occurrences,selectedSeller]);
 const availableItems=useMemo(()=>visibleItems.map(item=>{const sold=sales.filter(sale=>sale.remessa_item_id===item.id&&sale.status!=='cancelada').reduce((sum,sale)=>sum+sale.quantidade,0);const occurred=occurrences.filter(entry=>entry.remessa_item_id===item.id&&entry.status!=='cancelada').reduce((sum,entry)=>sum+entry.quantidade,0);return{...item,balance:item.quantidade_enviada-sold-occurred}}).filter(item=>item.balance>0&&visibleRemittances.find(remittance=>remittance.id===item.remessa_id)?.status.match(/recebida|parcialmente/)),[visibleItems,sales,occurrences,visibleRemittances]);
 const totals=useMemo(()=>({consigned:availableItems.reduce((sum,item)=>sum+item.balance,0),sales:sellerSales.filter(item=>item.status!=='cancelada').reduce((sum,item)=>sum+Number(item.valor_total),0),commission:sellerSales.filter(item=>item.status!=='cancelada').reduce((sum,item)=>sum+Number(item.valor_comissao),0)}),[availableItems,sellerSales]);
 const saleTotal=useMemo(()=>saleItems.reduce((sum,entry)=>sum+Number(entry.quantity||0)*Number(entry.unitValue||0),0),[saleItems]);
 const sellerOrders=useMemo(()=>{const seller=sellers.find(item=>item.id===selectedSeller);return seller?orders.filter(order=>order.vendedor_cadastro_id===seller.id||Boolean(seller.usuario_id&&order.vendedor_id===seller.usuario_id)):[]},[orders,sellers,selectedSeller]);
 const pickerCategories=useMemo(()=>Array.from(new Set(products.map(product=>product.categoria).filter((value):value is string=>Boolean(value)))).sort((a,b)=>a.localeCompare(b,'pt-BR')),[products]);
 const pickerProducts=useMemo(()=>{const query=pickerQuery.trim().toLocaleLowerCase('pt-BR');return products.filter(product=>(pickerCategory==='todos'||product.categoria===pickerCategory)&&(!query||product.nome.toLocaleLowerCase('pt-BR').includes(query)))},[pickerCategory,pickerQuery,products]);

 const originalReservedQuantity=useCallback((productId:string)=>editingRemittance&&['enviada','recebida','parcialmente_devolvida'].includes(editingRemittance.status)?Number(items.find(item=>item.remessa_id===editingRemittance.id&&item.produto_id===productId)?.quantidade_enviada||0):0,[editingRemittance,items]);
 const availableForDraft=useCallback((product:Product)=>product.estoque_disponivel+originalReservedQuantity(product.airtable_record_id),[originalReservedQuantity]);

 function resetRemittanceForm(){setEditingRemittance(null);setDraftItems([]);setShippingDate(new Date().toISOString().slice(0,10));setReturnDate('');setNotes('');setPickerOpen(false);setPickerQuery('');setPickerCategory('todos')}
 function startEditingRemittance(remittance:Remittance){
  setEditingRemittance(remittance);setSelectedSeller(remittance.vendedor_id);setShippingDate(remittance.data_envio);setReturnDate(remittance.data_prevista_retorno||'');setNotes(remittance.observacoes||'');
  setDraftItems(items.filter(item=>item.remessa_id===remittance.id).map(item=>({productId:item.produto_id,quantity:String(item.quantidade_enviada)})));setRemittanceMessage('');setTab('remittances');
  window.setTimeout(()=>document.querySelector('.remittance-form')?.scrollIntoView({behavior:'smooth',block:'start'}),0);
 }

 function toggleDraftProduct(productId:string,checked:boolean){setDraftItems(current=>checked?[...current.filter(item=>item.productId!==productId),{productId,quantity:'1'}]:current.filter(item=>item.productId!==productId))}
 function setDraftQuantity(productId:string,quantity:string){setDraftItems(current=>current.map(item=>item.productId===productId?{...item,quantity}:item))}
 function toggleSaleItem(item:Item&{balance:number},checked:boolean){setSaleItems(current=>checked?[...current.filter(entry=>entry.itemId!==item.id),{itemId:item.id,quantity:'1',unitValue:String(Number(item.preco_unitario))}]:current.filter(entry=>entry.itemId!==item.id))}
 function setSaleItemValue(itemId:string,field:'quantity'|'unitValue',value:string){setSaleItems(current=>current.map(entry=>entry.itemId===itemId?{...entry,[field]:value}:entry))}

 async function saveRemittance(event:React.SyntheticEvent<HTMLFormElement>){
  event.preventDefault();setRemittanceMessage('');
  const valid=draftItems.filter(item=>item.productId&&Number(item.quantity)>0);
  if(!selectedSeller||!valid.length){setRemittanceMessage('Selecione o vendedor e ao menos um produto.');return}
  const seller=sellers.find(item=>item.id===selectedSeller);
  if(!seller){setRemittanceMessage('O vendedor selecionado não está mais disponível. Atualize a tela e tente novamente.');return}
  const unavailable=valid.map(entry=>({entry,product:products.find(item=>item.airtable_record_id===entry.productId)})).find(({entry,product})=>!product||Number(entry.quantity)>availableForDraft(product));
  if(unavailable){const product=unavailable.product,available=product?availableForDraft(product):0;setRemittanceMessage(product?`${product.nome}: existem ${available} unidades disponíveis para esta remessa, mas foram solicitadas ${Number(unavailable.entry.quantity)}.`:'Um dos produtos selecionados não está mais disponível.');return}
  setCreating(true);
  try{
   if(editingRemittance){
    const updated=await supabase.rpc('farm_update_consignment',{p_remessa_id:editingRemittance.id,p_seller_id:selectedSeller,p_shipping_date:shippingDate,p_return_date:returnDate||null,p_notes:notes.trim()||null,p_items:valid.map(entry=>({produto_id:entry.productId,quantidade:Number(entry.quantity)}))});
    if(updated.error){setRemittanceMessage(updated.error.message);return}
    resetRemittanceForm();await load();setRemittanceMessage('Remessa alterada e reservas do estoque recalculadas.');return
   }
   const {data:remittance,error}=await supabase.from('farm_consignments').insert({vendedor_id:selectedSeller,ambiente:environment,data_envio:shippingDate,data_prevista_retorno:returnDate||null,observacoes:notes.trim()||null}).select('id').single();
   if(error||!remittance){setRemittanceMessage(`Não foi possível criar a remessa${error?.message?`: ${error.message}`:'.'}`);return}
   const rows=valid.map(entry=>{const product=products.find(item=>item.airtable_record_id===entry.productId);if(!product)throw new Error('Um dos produtos selecionados não está mais disponível.');return{remessa_id:remittance.id,produto_id:product.airtable_record_id,produto_nome:product.nome,categoria:product.categoria,foto_url:product.foto_urls?.[0]||null,quantidade_enviada:Number(entry.quantity),preco_unitario:Number(product.preco_venda||0),desconto_maximo_percentual:Number(product.desconto_maximo_percentual||0),percentual_comissao:Number(seller.percentual_comissao||0)}});
   const insert=await supabase.from('farm_consignment_items').insert(rows);
   if(insert.error){await supabase.from('farm_consignments').delete().eq('id',remittance.id);setRemittanceMessage(`Não foi possível incluir os produtos na remessa: ${insert.error.message}`);return}
   const sent=await supabase.rpc('farm_send_consignment',{p_remessa_id:remittance.id});
   if(sent.error){await supabase.from('farm_consignment_items').delete().eq('remessa_id',remittance.id);await supabase.from('farm_consignments').delete().eq('id',remittance.id);setRemittanceMessage(sent.error.message);return}
   resetRemittanceForm();await load();setRemittanceMessage('Remessa enviada e produtos reservados no estoque.');
  }catch(error){setRemittanceMessage(error instanceof Error?`Não foi possível enviar a remessa: ${error.message}`:'Não foi possível enviar a remessa. Tente novamente.')}
  finally{setCreating(false)}
 }
 async function deleteRemittance(remittance:Remittance){
  if(!window.confirm(`Excluir a remessa nº ${String(remittance.numero).padStart(5,'0')}? As quantidades reservadas voltarão ao estoque disponível.`))return;
  setWorkingRemittance(remittance.id);setRemittanceMessage('');
  try{const {error}=await supabase.rpc('farm_delete_consignment',{p_remessa_id:remittance.id});if(error){setRemittanceMessage(error.message);return}if(editingRemittance?.id===remittance.id)resetRemittanceForm();await load();setRemittanceMessage('Remessa excluída e quantidades reservadas liberadas no estoque.')}finally{setWorkingRemittance('')}
 }
 async function confirm(id:string){const {error}=await supabase.rpc('farm_confirm_consignment',{p_remessa_id:id});setMessage(error?error.message:'Recebimento confirmado.');if(!error)await load()}
 async function registerSale(event:React.SyntheticEvent<HTMLFormElement>){
  event.preventDefault();setMessage('');
  if(!saleItems.length){setMessage('Selecione ao menos uma peça para registrar a venda.');return}
  const invalid=saleItems.find(entry=>{const item=availableItems.find(candidate=>candidate.id===entry.itemId);return !item||Number(entry.quantity)<=0||Number(entry.quantity)>item.balance||Number(entry.unitValue)<0});
  if(invalid){setMessage('Revise as quantidades e os valores das peças selecionadas.');return}
  if(!paymentMethod){setMessage('Informe a forma de pagamento.');return}
  const invalidReceipt=receiptFiles.find(file=>!file.type.startsWith('image/')||file.size>8*1024*1024);
  if(invalidReceipt){setMessage(`${invalidReceipt.name}: envie uma imagem de até 8 MB.`);return}
  setRegistering(true);
  const groupId=crypto.randomUUID(),uploaded:string[]=[];
  try{
   for(const file of receiptFiles){const extension=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg',path=`${userId}/${groupId}/${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from('consignment-receipts').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;uploaded.push(path)}
   const result=await supabase.rpc('farm_register_consignment_sales',{p_items:saleItems.map(entry=>({item_id:entry.itemId,quantidade:Number(entry.quantity),valor_unitario:Number(entry.unitValue)})),p_sale_date:actionDate,p_customer_name:customer.trim()||null,p_notes:actionNotes.trim()||null,p_sale_group_id:groupId,p_payment_method:paymentMethod,p_receipt_paths:uploaded});
   if(result.error)throw result.error;
   const count=saleItems.length;setSaleItems([]);setReceiptFiles([]);setReceiptInputKey(current=>current+1);setCustomer('');setActionNotes('');await load();setMessage(`${count} ${count===1?'peça registrada':'peças registradas'} para o fechamento mensal.`);
  }catch(error){if(uploaded.length)await supabase.storage.from('consignment-receipts').remove(uploaded);setMessage(error instanceof Error?error.message:'Não foi possível registrar a venda. Tente novamente.')}finally{setRegistering(false)}
 }
 async function registerOccurrence(event:React.SyntheticEvent<HTMLFormElement>){
  event.preventDefault();setMessage('');if(!actionItem){setMessage('Selecione uma peça consignada.');return}setRegistering(true);
  try{const result=await supabase.rpc('farm_register_consignment_occurrence',{p_item_id:actionItem,p_type:actionType,p_quantity:Number(actionQty),p_date:actionDate,p_treatment:actionType==='devolucao'?null:treatment,p_responsibility_value:Number(responsibility||0),p_notes:actionNotes.trim()||null});setMessage(result.error?result.error.message:'Ocorrência registrada.');if(!result.error){setActionItem('');setActionQty('1');setActionNotes('');await load()}}finally{setRegistering(false)}
 }
 async function closeMonth(){if(!selectedSeller)return;const {error}=await supabase.rpc('farm_close_seller_month',{p_seller_id:selectedSeller,p_competence:`${competence}-01`,p_notes:null});setMessage(error?error.message:'Fechamento mensal aprovado.');if(!error)await load()}
 async function markPaid(id:string){const {error}=await supabase.from('farm_seller_closings').update({status:'pago',pago_em:new Date().toISOString(),atualizado_em:new Date().toISOString()}).eq('id',id);setMessage(error?'Não foi possível marcar como pago.':'Pagamento registrado.');if(!error)await load()}
 async function saveProductPolicy(event:React.SyntheticEvent<HTMLFormElement>){event.preventDefault();if(!policyProduct)return;const {error}=await supabase.from('farm_portfolio_products').update({desconto_maximo_percentual:Number(policyDiscount||0)}).eq('airtable_record_id',policyProduct);setMessage(error?'Não foi possível salvar o limite de desconto.':'Limite de desconto do produto atualizado.');if(!error)await load()}
 async function cancelSale(id:string){const {error}=await supabase.rpc('farm_cancel_consignment_sale',{p_sale_id:id});setMessage(error?error.message:'Venda cancelada e saldo consignado liberado.');if(!error)await load()}
 async function openReceipt(path:string){const preview=window.open('','_blank');const {data,error}=await supabase.storage.from('consignment-receipts').createSignedUrl(path,300);if(error||!data?.signedUrl){preview?.close();setMessage('Não foi possível abrir o comprovante.');return}if(preview)preview.location.href=data.signedUrl;else window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 async function exportManifest(remittance:Remittance){
  const remittanceItems=items.filter(item=>item.remessa_id===remittance.id),seller=sellers.find(item=>item.id===remittance.vendedor_id);
  const {jsPDF}=await import('jspdf');
  const doc=new jsPDF({unit:'mm',format:'a4'}),width=doc.internal.pageSize.getWidth();
  try{const response=await fetch(`${import.meta.env.BASE_URL}brand/Logo_Otimizada_Preta.png`),blob=await response.blob(),reader=new FileReader();const data=await new Promise<string>((resolve,reject)=>{reader.onload=()=>typeof reader.result==='string'?resolve(reader.result):reject(new Error('Imagem inválida'));reader.onerror=reject;reader.readAsDataURL(blob)});doc.addImage(data,'PNG',14,8,22,22)}catch{/* logo opcional */}
  doc.setTextColor(20,62,60);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Romaneio de Consignação',42,17);
  doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(`Remessa nº ${String(remittance.numero).padStart(5,'0')} · Envio ${date(remittance.data_envio)}`,42,24);
  doc.text(`Vendedor: ${seller?.nome||'—'}`,14,37);doc.text(`Previsão de retorno: ${date(remittance.data_prevista_retorno)}`,14,43);
  let y=54,total=0,totalCommission=0;
  for(const item of remittanceItems){
   if(y>267){doc.addPage();y=20}
   doc.setFillColor(246,248,248);doc.roundedRect(14,y,width-28,20,2,2,'F');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(item.produto_nome,18,y+6,{maxWidth:95});doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`${item.categoria||'Sem categoria'} · ${item.quantidade_enviada} un. × ${money.format(Number(item.preco_unitario))}`,18,y+13);doc.text(`Desconto máx. ${Number(item.desconto_maximo_percentual).toLocaleString('pt-BR')}% · Comissão ${Number(item.percentual_comissao).toLocaleString('pt-BR')}%`,width-18,y+13,{align:'right'});
   const itemTotal=item.quantidade_enviada*Number(item.preco_unitario);total+=itemTotal;totalCommission+=itemTotal*Number(item.percentual_comissao||0)/100;y+=24;
  }
  if(y>250){doc.addPage();y=20}
  doc.setFont('helvetica','bold');doc.text(`Valor total da remessa: ${money.format(total)}`,width-14,y+5,{align:'right'});doc.text(`Valor total da comissão: ${money.format(totalCommission)}`,width-14,y+12,{align:'right'});
  doc.setFont('helvetica','normal');doc.text('Recebido por: ____________________________________',14,y+30);doc.text('Data: ____/____/________',14,y+39);doc.save(`romaneio-${String(remittance.numero).padStart(5,'0')}.pdf`);
 }

 function renderSaleFields(){return <>
  <fieldset className="sale-item-picker"><legend>Peças da venda</legend><p className="muted">Marque uma ou mais peças e informe a quantidade e o valor unitário vendido.</p>{availableItems.length===0?<p className="empty-sale-items">Não há peças consignadas disponíveis para este vendedor.</p>:<div className="sale-item-grid">{availableItems.map(item=>{const selected=saleItems.find(entry=>entry.itemId===item.id),remittance=remittances.find(entry=>entry.id===item.remessa_id);return <article className={selected?'selected':''} key={item.id}><label className="sale-item-check" aria-label={`Selecionar ${item.produto_nome}`}><input type="checkbox" checked={Boolean(selected)} onChange={event=>toggleSaleItem(item,event.target.checked)}/><span><strong>{item.produto_nome}</strong><small>Remessa {remittance?String(remittance.numero).padStart(5,'0'):'—'} · saldo {item.balance}</small></span></label>{selected&&<div className="sale-item-values"><label>Quantidade<input type="number" min="1" max={item.balance} step="1" value={selected.quantity} onChange={event=>setSaleItemValue(item.id,'quantity',event.target.value)} required/></label><label>Valor unitário (R$)<input type="number" min="0" step="0.01" value={selected.unitValue} onChange={event=>setSaleItemValue(item.id,'unitValue',event.target.value)} required/></label></div>}</article>})}</div>}</fieldset>
  <div className="fields"><label>Forma de pagamento<select value={paymentMethod} onChange={event=>setPaymentMethod(event.target.value)} required><option value="Pix">Pix</option><option value="Dinheiro">Dinheiro</option><option value="Cartão de débito">Cartão de débito</option><option value="Cartão de crédito">Cartão de crédito</option><option value="Transferência">Transferência</option><option value="Outro">Outro</option></select></label><label>Cliente (opcional)<input value={customer} onChange={event=>setCustomer(event.target.value)} placeholder="Não informado por padrão"/></label></div>
  <label className="wide-field receipt-upload">Comprovantes de pagamento (opcional)<input key={receiptInputKey} type="file" accept="image/*" multiple onChange={event=>{const chosen=Array.from(event.target.files||[]),combined=[...receiptFiles,...chosen];setReceiptFiles(combined.slice(0,10));setReceiptInputKey(current=>current+1);if(combined.length>10)setMessage('É possível anexar até 10 comprovantes por venda.')}}/><small>Até 10 imagens, com no máximo 8 MB cada.</small></label>
  {receiptFiles.length>0&&<div className="receipt-list">{receiptFiles.map((file,index)=><span key={`${file.name}-${file.lastModified}-${index}`}>{file.name}<button type="button" aria-label={`Remover ${file.name}`} onClick={()=>setReceiptFiles(current=>current.filter((_,fileIndex)=>fileIndex!==index))}><X size={14}/></button></span>)}</div>}
  <div className="sale-total"><span>{saleItems.length} {saleItems.length===1?'peça selecionada':'peças selecionadas'} · {receiptFiles.length} {receiptFiles.length===1?'comprovante':'comprovantes'}</span><strong>Total da venda: {money.format(saleTotal)}</strong></div>
 </>}

 if(loading)return <section className="panel sellers-state">Carregando consignações…</section>;
 return <section className="sellers-module"><div className="sellers-toolbar"><div className="seller-filter"><label>Vendedor<select value={selectedSeller} onChange={event=>setSelectedSeller(event.target.value)}>{sellers.map(seller=><option key={seller.id} value={seller.id}>{seller.nome}</option>)}</select></label></div><button className="secondary" onClick={()=>void load(true)}><RefreshCw size={16}/> Atualizar</button></div>
  <div className="seller-kpis"><article><span>Peças com vendedor</span><strong>{totals.consigned}</strong></article><article><span>Vendas registradas</span><strong>{money.format(totals.sales)}</strong></article><article><span>Comissão acumulada</span><strong>{money.format(totals.commission)}</strong></article></div>
  <div className="seller-tabs" role="tablist">{([['overview','Visão geral'],['remittances','Remessas'],['sales','Vendas e devoluções'],['closings','Fechamentos']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{message&&<output className="notice">{message}</output>}
  {tab==='overview'&&<div className="seller-overview-grid">
   <form className="panel consignment-action-form seller-quick-sale" onSubmit={registerSale}><div className="quick-sale-title"><div><h2>Registrar venda</h2><p className="muted">Selecione todas as peças da venda e anexe os comprovantes do pagamento.</p></div><ShoppingBag size={24}/></div><div className="fields"><label>Data da venda<input type="date" value={actionDate} onChange={event=>setActionDate(event.target.value)} required/></label></div>{renderSaleFields()}<label className="wide-field">Observações<textarea rows={2} value={actionNotes} onChange={event=>setActionNotes(event.target.value)}/></label><button disabled={registering||saleItems.length===0}>{registering?'Registrando…':`Registrar venda (${saleItems.length})`}</button></form>
   <section className="panel"><h2>Saldo consignado</h2>{availableItems.length===0?<p className="muted">Nenhuma peça disponível com este vendedor.</p>:availableItems.map(item=><article className="consigned-row" key={item.id}>{item.foto_url?<img src={item.foto_url} alt=""/>:<span className="item-placeholder"/>}<div><strong>{item.produto_nome}</strong><small>{item.categoria||'Sem categoria'}</small></div><b>{item.balance} un.</b></article>)}</section>
   <section className="panel"><h2>Atividade recente</h2>{sellerSales.slice(0,6).map(sale=><article className="activity-row" key={sale.id}><ShoppingBag size={17}/><span>{sale.quantidade} un. · {date(sale.data_venda)}<small>{sale.forma_pagamento?` · ${sale.forma_pagamento}`:''}</small></span><strong>{money.format(Number(sale.valor_total))}</strong></article>)}{sellerSales.length===0&&<p className="muted">Ainda não há vendas registradas.</p>}</section>
   <section className="panel seller-orders"><h2>Pedidos do vendedor</h2>{sellerOrders.length===0?<p className="muted">Nenhum pedido vinculado a este vendedor.</p>:sellerOrders.slice(0,8).map(order=><article className="activity-row" key={order.id}><ShoppingBag size={17}/><span>Pedido {String(order.numero).padStart(4,'0')} · {order.cliente_nome}<small>{order.status.replaceAll('_',' ')}</small></span><strong>{money.format(Number(order.valor_total||0))}</strong></article>)}</section>
  </div>}
  {tab==='remittances'&&<>
   <div className="section-title"><div><h2>Remessas de peças</h2><p className="muted">Os itens enviados ficam reservados no estoque e o romaneio registra os preços da remessa.</p></div></div>
   {administrator&&<>
    <form className="panel product-policy-form" onSubmit={saveProductPolicy}><h3>Limite de desconto por produto</h3><div className="fields"><label>Produto<select value={policyProduct} onChange={event=>{const id=event.target.value,product=products.find(item=>item.airtable_record_id===id);setPolicyProduct(id);setPolicyDiscount(String(product?.desconto_maximo_percentual||0))}} required><option value="">Selecione</option>{products.map(product=><option key={product.airtable_record_id} value={product.airtable_record_id}>{product.nome}</option>)}</select></label><label>Desconto máximo (%)<input type="number" min="0" max="100" step="0.01" value={policyDiscount} onChange={event=>setPolicyDiscount(event.target.value)} required/></label></div><button>Salvar limite</button></form>
    <form className={`panel remittance-form${editingRemittance?' editing-remittance':''}`} onSubmit={saveRemittance}>
     <div className="remittance-form-title"><div><h3>{editingRemittance?`Alterar remessa nº ${String(editingRemittance.numero).padStart(5,'0')}`:'Nova remessa'}</h3>{editingRemittance&&<p className="muted">Ao salvar, as reservas do estoque serão recalculadas.</p>}</div>{editingRemittance&&<button type="button" className="secondary" onClick={resetRemittanceForm}><X size={16}/> Cancelar edição</button>}</div>
     <div className="fields"><label>Data de envio<input type="date" value={shippingDate} onChange={event=>setShippingDate(event.target.value)} required/></label><label>Previsão de retorno<input type="date" value={returnDate} onChange={event=>setReturnDate(event.target.value)}/></label></div>
     <button type="button" className="secondary portfolio-picker-button" onClick={()=>setPickerOpen(true)}><PackagePlus size={16}/> Selecionar produtos no Portfólio</button>
     {draftItems.length===0?<p className="muted">Nenhum produto selecionado.</p>:<div className="selected-remittance-products">{draftItems.map(entry=>{const product=products.find(item=>item.airtable_record_id===entry.productId);if(!product)return null;const available=availableForDraft(product),insufficient=Number(entry.quantity)>available;return <article className={insufficient?'insufficient-stock':''} key={entry.productId}>{product.foto_urls?.[0]?<img src={product.foto_urls[0]} alt=""/>:<span className="item-placeholder"/>}<div><strong>{product.nome}</strong><small>{product.categoria||'Sem categoria'} · {available} disponíveis para esta remessa</small>{insufficient&&<small className="stock-warning">Reduza a quantidade para continuar.</small>}</div><label>Quantidade<input type="number" min="1" max={Math.max(available,1)} step="1" value={entry.quantity} onChange={event=>setDraftQuantity(entry.productId,event.target.value)}/></label><button type="button" className="secondary" onClick={()=>toggleDraftProduct(entry.productId,false)}>Remover</button></article>})}</div>}
     <label className="wide-field">Observações<textarea value={notes} onChange={event=>setNotes(event.target.value)} rows={2}/></label>
     <button disabled={creating||draftItems.length===0}>{creating?(editingRemittance?'Salvando…':'Enviando…'):(editingRemittance?'Salvar alterações':'Criar, reservar e enviar remessa')}</button>
     {remittanceMessage&&<output className="notice remittance-notice" aria-live="polite">{remittanceMessage}</output>}
    </form>
   </>}
   <div className="remittance-list">{visibleRemittances.map(remittance=><article className="panel remittance-card" key={remittance.id}><div><small>REMESSA Nº {String(remittance.numero).padStart(5,'0')}</small><h3>{date(remittance.data_envio)}</h3><span className="status-chip active">{statusLabel[remittance.status]||remittance.status}</span></div><p>{items.filter(item=>item.remessa_id===remittance.id).reduce((sum,item)=>sum+item.quantidade_enviada,0)} peças · retorno {date(remittance.data_prevista_retorno)}</p><div className="actions"><button className="secondary" onClick={()=>void exportManifest(remittance)}><Download size={16}/> Romaneio PDF</button>{administrator&&<button className="secondary" disabled={workingRemittance===remittance.id} onClick={()=>startEditingRemittance(remittance)}><Pencil size={16}/> Alterar</button>}{administrator&&<button className="danger-button remittance-delete" disabled={workingRemittance===remittance.id} onClick={()=>void deleteRemittance(remittance)}><Trash2 size={16}/> {workingRemittance===remittance.id?'Excluindo…':'Excluir'}</button>}{remittance.status==='enviada'&&<button onClick={()=>void confirm(remittance.id)}><Check size={16}/> Confirmar recebimento</button>}</div></article>)}</div>
  </>}
  {tab==='sales'&&<>
   <form className="panel consignment-action-form" onSubmit={actionType==='sale'?registerSale:registerOccurrence}>
    <h2>Registrar movimentação</h2>
    <div className="fields"><label>Tipo<select value={actionType} onChange={event=>{setActionType(event.target.value as typeof actionType);setMessage('')}}><option value="sale">Venda</option><option value="devolucao">Devolução</option><option value="perda">Perda</option><option value="avaria">Avaria</option></select></label><label>Data<input type="date" value={actionDate} onChange={event=>setActionDate(event.target.value)} required/></label></div>
    {actionType==='sale'?renderSaleFields():<div className="fields"><label>Peça<select value={actionItem} onChange={event=>setActionItem(event.target.value)} required><option value="">Selecione</option>{availableItems.map(item=><option key={item.id} value={item.id}>{item.produto_nome} · saldo {item.balance}</option>)}</select></label><label>Quantidade<input type="number" min="1" step="1" value={actionQty} onChange={event=>setActionQty(event.target.value)} required/></label>{actionType!=='devolucao'&&<><label>Tratamento no fechamento<select value={treatment} onChange={event=>setTreatment(event.target.value)}><option value="absorvido_farm">Absorvido pela Farm</option><option value="cobrado_vendedor">Cobrado do vendedor</option><option value="compartilhado">Compartilhado</option><option value="outro">Outro</option></select></label><label>Responsabilidade do vendedor (R$)<input type="number" min="0" step="0.01" value={responsibility} onChange={event=>setResponsibility(event.target.value)}/></label></>}</div>}
    <label className="wide-field">Observações<textarea rows={2} value={actionNotes} onChange={event=>setActionNotes(event.target.value)}/></label><button disabled={registering||(actionType==='sale'&&saleItems.length===0)}>{registering?'Registrando…':actionType==='sale'?`Registrar venda (${saleItems.length})`:'Registrar ocorrência'}</button>
   </form>
   <div className="seller-activity-list">{sellerSales.map(sale=><article className="panel" key={sale.id}><ShoppingBag size={18}/><div><strong>{items.find(item=>item.id===sale.remessa_item_id)?.produto_nome||'Venda'} · {date(sale.data_venda)}</strong><small>{sale.quantidade} un. {sale.cliente_nome?`· ${sale.cliente_nome}`:''}{sale.forma_pagamento?` · ${sale.forma_pagamento}`:''}</small>{sale.comprovante_paths?.length>0&&<span className="receipt-links">{sale.comprovante_paths.map((path,index)=><button type="button" className="secondary" key={path} onClick={()=>void openReceipt(path)}>Comprovante {index+1}</button>)}</span>}</div><b>{money.format(Number(sale.valor_total))}</b><span>{statusLabel[sale.status]||sale.status}</span>{sale.status==='informada'&&<button className="secondary sale-cancel" onClick={()=>void cancelSale(sale.id)}>Cancelar</button>}</article>)}{sellerOccurrences.map(entry=><article className="panel" key={entry.id}><Undo2 size={18}/><div><strong>{entry.tipo} · {date(entry.data_ocorrencia)}</strong><small>{entry.quantidade} un. · {entry.tratamento?.replaceAll('_',' ')||'Retorno ao estoque'}</small></div><b>{money.format(Number(entry.valor_responsabilidade))}</b><span>{statusLabel[entry.status]||entry.status}</span></article>)}</div>
  </>}
  {tab==='closings'&&<><section className="panel closing-form"><h2>Fechamento mensal</h2><p className="muted">Confirme as vendas, perdas e avarias do mês. A comissão usa o valor final efetivamente vendido.</p>{administrator&&<div className="actions"><label>Competência<input type="month" value={competence} onChange={event=>setCompetence(event.target.value)}/></label><button onClick={()=>void closeMonth()}><WalletCards size={16}/> Aprovar fechamento</button></div>}</section><div className="closing-list">{closings.filter(item=>!selectedSeller||item.vendedor_id===selectedSeller).map(closing=><article className="panel" key={closing.id}><div><small>{new Date(`${closing.competencia}T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</small><h3>{statusLabel[closing.status]||closing.status}</h3></div><dl><div><dt>Vendas</dt><dd>{money.format(Number(closing.total_vendas))}</dd></div><div><dt>Comissão</dt><dd>{money.format(Number(closing.total_comissao))}</dd></div><div><dt>Perdas cobradas</dt><dd>{money.format(Number(closing.total_responsabilidades))}</dd></div><div><dt>Repasse</dt><dd>{money.format(Number(closing.valor_liquido))}</dd></div></dl>{administrator&&closing.status==='aprovado'&&<button onClick={()=>void markPaid(closing.id)}>Marcar como pago</button>}</article>)}</div></>}
  {pickerOpen&&<dialog open className="consignment-picker-backdrop" aria-label="Selecionar produtos do portfólio"><section className="panel consignment-picker"><div className="orders-title"><div><h2>Selecionar produtos</h2><p className="muted">Marque as peças e informe a quantidade da remessa.</p></div><button type="button" className="secondary" onClick={()=>setPickerOpen(false)}>Concluir seleção</button></div><div className="consignment-picker-filters"><label>Buscar<input value={pickerQuery} onChange={event=>setPickerQuery(event.target.value)} placeholder="Nome do produto"/></label><label>Categoria<select value={pickerCategory} onChange={event=>setPickerCategory(event.target.value)}><option value="todos">Todas</option>{pickerCategories.map(category=><option key={category}>{category}</option>)}</select></label></div><div className="consignment-product-grid">{pickerProducts.map(product=>{const selected=draftItems.find(item=>item.productId===product.airtable_record_id),available=availableForDraft(product),unavailable=available<=0;return <article className={`${selected?'selected ':''}${unavailable?'unavailable':''}`.trim()} key={product.airtable_record_id}>{product.foto_urls?.[0]?<img src={product.foto_urls[0]} alt=""/>:<span className="item-placeholder"/>}<div><strong>{product.nome}</strong><small>{product.categoria||'Sem categoria'}</small><span>{money.format(Number(product.preco_venda||0))} · {available} disponíveis</span></div><label className="product-check"><input type="checkbox" checked={Boolean(selected)} disabled={unavailable&&!selected} onChange={event=>toggleDraftProduct(product.airtable_record_id,event.target.checked)}/> {unavailable?'Sem estoque':'Selecionar'}</label>{selected&&<label className="product-quantity">Quantidade<input type="number" min="1" max={Math.max(available,1)} step="1" value={selected.quantity} onChange={event=>setDraftQuantity(product.airtable_record_id,event.target.value)}/></label>}</article>})}</div>{pickerProducts.length===0&&<p className="muted">Nenhum produto encontrado.</p>}<button type="button" onClick={()=>setPickerOpen(false)}>Usar {draftItems.length} {draftItems.length===1?'produto selecionado':'produtos selecionados'}</button></section></dialog>}
 </section>;
}
