create table if not exists public.farm_sellers (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  telefone text,
  email text,
  usuario_id uuid references public.farm_profiles(id) on delete set null,
  ativo boolean not null default true,
  ambiente text not null default 'desenvolvimento'
    check (ambiente in ('desenvolvimento', 'producao')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (usuario_id, ambiente)
);

create table if not exists public.farm_orders (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_nome text not null,
  vendedor_id uuid references public.farm_profiles(id),
  vendedor_cadastro_id uuid references public.farm_sellers(id) on delete set null,
  vendedor_nome text not null,
  cliente_telefone text,
  cliente_email text,
  cliente_documento text,
  endereco_entrega text,
  data_pedido date not null default current_date,
  prazo_solicitado date,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  desconto_percentual numeric(5,2) not null default 0
    check (desconto_percentual between 0 and 100),
  valor_venda_informado numeric(12,2)
    check (valor_venda_informado is null or valor_venda_informado >= 0),
  valor_total numeric(12,2) not null default 0 check (valor_total >= 0),
  forma_pagamento text,
  observacoes text,
  motivo_cancelamento text,
  cancelado_em timestamptz,
  cancelado_por uuid references public.farm_profiles(id) on delete set null,
  status text not null default 'rascunho' check (status in (
    'rascunho', 'aguardando_precificacao', 'em_precificacao', 'precificado',
    'aguardando_confirmacao_vendedor', 'aguardando_aprovacao', 'devolvido_ajuste',
    'reprovado', 'aprovado', 'em_producao', 'pronto', 'entregue', 'cancelado'
  )),
  ambiente text not null default 'desenvolvimento'
    check (ambiente in ('desenvolvimento', 'producao')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.farm_order_items (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.farm_orders(id) on delete cascade,
  produto_id text references public.farm_portfolio_products(airtable_record_id) on delete set null,
  produto_nome text not null,
  quantidade integer not null default 1 check (quantidade > 0),
  preco_unitario numeric(12,2) not null default 0 check (preco_unitario >= 0),
  criado_em timestamptz not null default now()
);

-- As políticas aplicadas no Supabase permitem ao administrador consultar todos os
-- vendedores e pedidos. Cada vendedor vinculado a um usuário acessa somente os
-- próprios pedidos e pode alterá-los apenas nos estados editáveis do fluxo.
